### DISCUSSION TITLE
Custom my autoscaling

### DISCUSSION THREAD

**Discussion by kwanwoo02** [triton-inference-server/server#5797] [Q&A]
What I want is to scale up if the gpu memory usage is over 90% in the autoscaling process and scale down if it is less than 60%.

I modified depoly/k8s-onprem/values.yaml a bit and changed it to the following. Currently, if it is 90%, it seems to scale up and down.
Please check if it is correct. And I wish I could tell you how to do what I want. with yaml file

```yaml
autoscaling:
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Pods
      pods:
        metric:
          name: avg_gpu_memory_used
        target:
          type: AverageValue
          averageValue: 90
          
prometheus-adapter:
  prometheus:
    url: http://example-metrics-kube-prome-prometheus.default.svc.cluster.local
    port: 9090
  rules:
    custom:
      - seriesQuery: 'nv_gpu_memory_used_bytes{namespace="default",pod!=""}'
        resources:
          overrides:
            namespace:
              resource: "namespace"
            pod:
              resource: "pod"
        name:
          matches: "nv_gpu_memory_used_bytes"
          as: "avg_gpu_memory_used"
        metricsQuery: 'ceil((nv_gpu_memory_used_bytes/nv_gpu_memory_total_bytes)*100)' 
```
