### DISCUSSION TITLE
when i sead a triton inference request,  No trace data is obtained after the opentelemetry integration.

### DISCUSSION THREAD

**Discussion by Leelongqi** [triton-inference-server/server#6580] [Q&A] [answered]
can you give me a sample, just like a docker-compose.yml , eg ... thanks
![image](https://github.com/triton-inference-server/server/assets/33893308/6ead3a30-a3fb-4b29-bbe8-f032ffb6db37)

**Comment by Leelongqi** [comment, marked as answer]
Triton-inference-server config:
get trace data config: https://github.com/triton-inference-server/server/discussions/5909
Opentelemetry config:
http receiver config:  https://github.com/open-telemetry/opentelemetry-collector/issues/5187

**Reply by oandreeva-nv** [reply]
Thanks for linking discussions with the solutions!

**Comment by MatthieuToulemont** [comment]
Coming back here, as I had some issues setting it up for propagated tracing with Datadog. In the end here is what worked for me: 

```
- "tritonserver"
      - --trace-config
      - mode=opentelemetry
      - "--trace-config"
      - opentelemetry,url=http://dogstatsd:4318/v1/traces # replace with your datadog agent
      - "--trace-config"
      - rate=1
      - --trace-config
      - level=TIMESTAMPS
      - "--model-control-mode=explicit" # Personal preference
      - "--model-repository=PATH" # Personal preference
      - "--metrics-config"
      - "summary_latencies=true"
      - "--log-verbose=1"
      - "--log-warning=1"
      - "--log-error=1"
      - "--load-model=*"


dogstatsd:
    image: datadog/agent:7
    environment:
     - DD_APM_ENABLED=true
     - DD_PROCESS_AGENT_ENABLED=true
     - DD_APM_NON_LOCAL_TRAFFIC=true
     - DD_TRACE_OTEL_ENABLED=true 
     - DD_LOGS_ENABLED=true
     - DD_OTLP_CONFIG_LOGS_ENABLED=true
     - DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_HTTP_ENDPOINT=0.0.0.0:4318 # Important detail
```

If you use ddtrace==2.9.1  you won't need to implement the inject logic when calling triton
