### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by turowicz** [triton-inference-server/server#2300]
**Description**
RAM usage builds up with time reaching 100% after a few days. VRAM usage is as expected.

```  

...

root@docker-desktop:/workspaces/project.backend# kubectl top pod project-cognition-api-5d4bc4f657-btf4n
NAME                                     CPU(cores)   MEMORY(bytes)   
project-cognition-api-5d4bc4f657-btf4n   960m         4544Mi          
root@docker-desktop:/workspaces/project.backend# kubectl top pod project-cognition-api-5d4bc4f657-btf4n
NAME                                     CPU(cores)   MEMORY(bytes)   
project-cognition-api-5d4bc4f657-btf4n   971m         4563Mi          
root@docker-desktop:/workspaces/project.backend# kubectl top pod project-cognition-api-5d4bc4f657-btf4n
NAME                                     CPU(cores)   MEMORY(bytes)   
project-cognition-api-5d4bc4f657-btf4n   963m         4567Mi               
root@docker-desktop:/workspaces/project.backend# kubectl top pod project-cognition-api-5d4bc4f657-btf4n
NAME                                     CPU(cores)   MEMORY(bytes)   
project-cognition-api-5d4bc4f657-btf4n   963m         4586Mi   
root@docker-desktop:/workspaces/project.backend# kubectl top pod project-cognition-api-5d4bc4f657-btf4n
NAME                                     CPU(cores)   MEMORY(bytes)   
project-cognition-api-5d4bc4f657-btf4n   963m         4595Mi  
 
...

```

**Triton Information**
20.11-py3 on k8s 1.19.x with Ubuntu 18.04 and CUDA 11.1.

```
+------------+-----------------------------------------------------------------+------+
| Backend    | Config                                                          | Path |
+------------+-----------------------------------------------------------------+------+
| tensorflow | /opt/tritonserver/backends/tensorflow1/libtriton_tensorflow1.so | {}   |
+------------+-----------------------------------------------------------------+------+
I1130 12:46:33.330306 1 server.cc:184] 
+--------------------------+---------+--------+
| Model                    | Version | Status |
+--------------------------+---------+--------+
| 20200918.1_GCPIRCT       | 1050000 | READY  |
| faster_rcnn_inception_v2 | 1       | READY  |
+--------------------------+---------+--------+
I1130 12:46:33.330355 1 tritonserver.cc:1620] 
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------+
| Option                           | Value                                                                                                                                              |
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------+
| server_id                        | triton                                                                                                                                             |
| server_version                   | 2.5.0                                                                                                                                              |
| server_extensions                | classification sequence model_repository schedule_policy model_configuration system_shared_memory cuda_shared_memory binary_tensor_data statistics |
| model_repository_path[0]         | /models                                                                                                                                            |
| model_control_mode               | MODE_NONE                                                                                                                                          |
| strict_model_config              | 0                                                                                                                                                  |
| pinned_memory_pool_byte_size     | 268435456                                                                                                                                          |
| cuda_memory_pool_byte_size{0}    | 67108864                                                                                                                                           |
| min_supported_compute_capability | 6.0                                                                                                                                                |
| strict_readiness                 | 1                                                                                                                                                  |
| exit_timeout                     | 30                                                                                                                                                 |
+----------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------+
```

Running in K8S using the following template. Recently removed the memory and ustack flags as per new documentation.

```
{{- $fullName := printf "%s-cognition-api" .Release.Name -}}
{{- $version := printf "v%s" .Values.cognitionApi.image.tag -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
  labels:
    app.kubernetes.io/name: {{ $fullName }}
    app.kubernetes.io/version: {{ $version }}
    helm.sh/chart: {{ include "MegaChart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.cognitionApi.replicaCount }}
  selector:
    matchLabels:
      app: deployment
      app.kubernetes.io/name: {{ $fullName }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: deployment
        app.kubernetes.io/name: {{ $fullName }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 30
      volumes:
        - name: "{{ $fullName }}-models"
          hostPath:
            path: /models
            type: Directory
      containers:
        - name: {{ $fullName }}
          image: "{{ .Values.cognitionApi.image.repository }}:{{ .Values.cognitionApi.image.tag }}"
          imagePullPolicy: {{ .Values.pullPolicy }}
          args: 
            - "tritonserver"
            - "--model-repository=/models"
            - "--strict-model-config=false"
          ports:
            - name: http
              containerPort: 8000
            - name: grpc
              containerPort: 8001
            - name: metrics
              containerPort: 8002
          livenessProbe:
            httpGet:
              path: /v2/health/live
              port: http
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            httpGet:
              path: /v2/health/ready
              port: http
          securityContext:
            runAsUser: 1000
          env:
            - name: AppSettings__Version
              value: {{ $version }}            
          volumeMounts:
            - mountPath: /models
              name: "{{ $fullName }}-models"
          resources:
{{ toYaml .Values.cognitionApi.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
```

**To Reproduce**
Host a TensorFlow 1.x model in GPU.

Object detection using F-RCNN inception v2 from the model zoo.

**Expected behaviour**
System RAM to fluctuate around a constant value, not consuming all RAM.

cc @deadeyegoodwin
