### ISSUE TITLE
Declaring Triton plugins, with kfserving

### ISSUE THREAD

**Issue by ontheway16** [triton-inference-server/server#2421]
Hi, I am using a Triton setup which utilizes a .so plugin file. Currently, I can make it working as a pod, via helm install.
I am trying to run same server under k8s/kfserving inferenceservice. I have setup necessary pv and pvc files for both model and plugins, and it successfully loads models, but I could not decide where/how to declare the plugins pvc:// in inferenceservice yaml file, to make it load the plug-in, under kfserving. Any pointers appreciated !

**Comment by ontheway16** [comment]
And this is the current form of kfserving inferenceservice:

```
apiVersion: "serving.kubeflow.org/v1beta1"
kind: "InferenceService"
metadata:
  name: "test-triton"
spec:
  predictor:
    triton:
      runtimeVersion: 20.08-py3
      resources:
        limits:
          nvidia.com/gpu: "1"
          memory: 5Gi
        requests:
          nvidia.com/gpu: "1"
          memory: 1Gi
      storageUri: "pvc://triton-models-claim2/"
```
