### ISSUE TITLE
Error at Triton init on GKE while loading Pytorch custom ops

### ISSUE THREAD

**Issue by gilevir** [triton-inference-server/server#2596]
**Description**
When running triton on GKE from a custom Docker image and setting right Env variables, error shows when deploying:
```
ERROR: ld.so: object '/opt/tritonserver/torch_extensions/custom_op1.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
```

**Triton Information**
Triton version 2.5.0

**To Reproduce**
Build new Triton image containing custom ops as follow : 

- Build a custom image as follow :

```
FROM nvcr.io/nvidia/tritonserver:20.11-py3
RUN mkdir /opt/tritonserver/torch_extensions
COPY ./torch_extensions /opt/tritonserver/torch_extensions
```
where torch_extensions folder contains the custom ops `.so` files.

- Deploy triton on GKE following https://github.com/triton-inference-server/server/tree/master/deploy/single_server

The env var are set in the `deployment.yaml` file as follows:
```
args: ["tritonserver", "--model-store={{ .Values.image.modelRepositoryPath }}", "--model-control-mode=explicit", "--exit-on-error=true", "--log-warning=true", "--log-error=true", "--log-info=true"]
          env:
            - name: LD_LIBRARY_PATH
              value: /opt/tritonserver/lib/pytorch/:/usr/local/cuda/compat/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64:/opt/tritonserver/lib/pytorch
            - name: LD_PRELOAD
              value: /opt/tritonserver/torch_extensions/custom_op1.so:/opt/tritonserver/torch_extensions/custom_op2.so
```

**Expected behavior**
No error while deploying
