### ISSUE TITLE
Not able to run custom PyTorch model using Triton Inference Server & Seldon Core

### ISSUE THREAD

**Issue by altruistcoder** [triton-inference-server/server#2637]
Hey, 

I am trying to deploy a ML model trained on **CIFAR10** dataset using **PyTorch** as a Rest API on my Openshift cluster using **Seldon** Operator provided in the OperatorHub of my cluster which itself is using the **Triton Inference Server** at the bottom, but I am facing some errors when trying to deploy it.

I have **attached the output of the logs of my Pod** which shows the error which I am facing.

First, I tried to deploy a sample Pytorch model using a sample Seldon Deployment Definition file provided by Seldon in this [triton examples notebook](https://github.com/SeldonIO/seldon-core/blob/master/notebooks/triton_examples.ipynb) and it worked fine and I was able to take predictions from the deployed model successfully.

The Seldon Definition File used in this sample is as follows:

```
apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: cifar10
  namespace: seldon
spec:
  annotations:
    seldon.io/engine-seldon-log-messages-externally: "true"
  name: resnet32
  predictors:
  - graph:
      implementation: TRITON_SERVER
      logger:
        mode: all
      modelUri: gs://seldon-models/triton/pytorch_cifar10
      serviceAccountName: s3-sa
      name: cifar10
      type: MODEL
    name: default
    replicas: 1
  protocol: kfserving
```

This sample definition is referring to an already trained model on CIFAR10 dataset which is stored in the google bucket and accessible publicly.

But, in my case I have trained my own model on the CIFAR10 dataset only and stored the trained model in my `Rook-Ceph bucket` which is an **S3-compatible storage solution** in my Openshift cluster. Hence, the only difference in the above definition file comes that instead of writing value of ***modelUri*** as `gs://seldon-models/triton/pytorch_cifar10`, I am writing the value of ***modelUri*** as `s3://<bucket_name_here>/pytorch_cifar10`. And, this is causing the above issue to happen.

The model repository structure for my model (stored in my S3 bucket) is as follows:

![image](https://user-images.githubusercontent.com/31319270/111533162-7dc27800-878c-11eb-8935-08dbc7a7c614.png)

The contents of the *config.pbtxt file* are present below for reference:
```
name: "cifar10"
platform: "pytorch_libtorch"
max_batch_size: 8
input [
    {
      name: "input__0"
      data_type: TYPE_FP32
      dims: [ 3, 32, 32 ]
    }
]
output [
 {
   name: "output__0"
   data_type: TYPE_FP32
   dims: [ 10 ]
 }
]
```

I confirmed that I am using the right model repository structure from the information given by Triton [here](https://github.com/triton-inference-server/server/blob/r21.02/docs/model_repository.md)
But, I am not able to find the reason why my model is not getting deployed when the only difference is in the location where the model is stored.

Can anyone please help me in resolving this issue as I am not able to proceed in my task and stuck on this from quite some time now?

[cifar10_pod_logs.txt](https://github.com/triton-inference-server/server/files/6159458/cifar10_pod_logs.txt)
