### ISSUE TITLE
Docker fails to register cuda shared memory

### ISSUE THREAD

**Issue by PauloFavero** [triton-inference-server/server#3429]
**Description**

The Triton client is unable to register Cuda shared memory when running the script from the docker command. Although, it works when running the docker in interactive mode.

**Triton Information**
What version of Triton are you using?

Server: nvcr.io/nvidia/tritonserver:21.03-py3
Client: nvcr.io/nvidia/tritonserver:21.03-py3-sdk

Are you using the Triton container or did you build it yourself? I am using the Triton container

Dockerfile.client
```
FROM  nvcr.io/nvidia/tritonserver:21.03-py3-sdk

RUN apt update && apt install -y libb64-dev ffmpeg
```

docker-compose.yml

```yml
version: '2.3'

services:
  triton-server:
    container_name: triton-server
    image: nvcr.io/nvidia/tritonserver:21.03-py3
    privileged: true
    runtime: nvidia
    shm_size: '2gb'
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    ipc: host
    ulimits:
      stack: 67108864
      memlock: -1
    environment:
      - LD_PRELOAD=/plugins/liblayerplugin.so
      - log-verbose=4
    command: bash -c "tritonserver --model-repository=/models --strict-model-config=false --grpc-infer-allocation-pool-size=16"

  triton-client:
    container_name: triton-client
    build:
      context: .
    network_mode: 'host'
    working_dir: /app/src
    depends_on:
      - triton-server
    environment:
      - log-verbose=4
    privileged: true
    runtime: nvidia
    shm_size: '2gb'
    command: bash -c "python3 simple_grpc_cudashm_client.py --verbose"
```

**To Reproduce**

Build the client container and then, run `docker-compose up`.  The triton-client container will execute the script  **simple_grpc_cudashm_client.py** but it will throw the following error:

```bash
unregister_system_shared_memory, metadata ()
triton-client    | 
triton-client    | Unregistered all system shared memory regions
triton-client    | unregister_cuda_shared_memory, metadata ()
triton-client    | 
triton-client    | Unregistered all cuda shared memory regions
triton-client    | register_cuda_shared_memory, metadata ()
triton-client    | name: "output0_data"
triton-client    | raw_handle: "\260iu\001\000\000\000\000\001\000\000\000\000\000\000\000\000\0002\000\000\000\000\000 \003\000\000\000\000\000\000\000\000\000\000\000\001\000\000\000\000\000\0001\000\000\000\000\000\000\000\242\000\320\301\216\000\000\\\000\000\000\000"
triton-client    | byte_size: 3276800
triton-client    | 
triton-client    | Traceback (most recent call last):
triton-client    |   File "simple_grpc_cudashm_client.py", line 61, in <module>
triton-client    |     triton_client.register_cuda_shared_memory(
triton-client    |   File "/usr/local/lib/python3.8/dist-packages/tritonclient/grpc/__init__.py", line 906, in register_cuda_shared_memory
triton-client    |     raise_error_grpc(rpc_error)
triton-client    |   File "/usr/local/lib/python3.8/dist-packages/tritonclient/grpc/__init__.py", line 61, in raise_error_grpc
triton-client    |     raise get_error_grpc(rpc_error) from None
triton-client    | tritonclient.utils.InferenceServerException: [StatusCode.INVALID_ARGUMENT] failed to register CUDA shared memory region 'output0_data'
```

The curious thing happens when I run the script from inside the container. If you run the container with `docker-compose run triton-client bash` and the from the terminal inside the container you execute `python3  simple_grpc_cudashm_client.py --verbose, the client works as expected without errors. This is the output generated in this case:

```bash
unregister_system_shared_memory, metadata ()

Unregistered all system shared memory regions
unregister_cuda_shared_memory, metadata ()

Unregistered all cuda shared memory regions
register_cuda_shared_memory, metadata ()
name: "output0_data"
raw_handle: " 3\225\001\000\000\000\000\t\000\000\000\000\000\000\000\000\0002\000\000\000\000\000 \003\000\000\000\000\000\000\000\000\000\000\000\001\000\000\000\000\000\0001\000\000\000\000\000\000\000\304\000\320\301\216\000\000\\\000\000\000\000"
byte_size: 3276800

Registered cuda shared memory with name 'output0_data'
register_cuda_shared_memory, metadata ()
name: "input0_data"
raw_handle: " 3\225\001\000\000\000\000\t\000\000\000\000\000\000\000\000\0002\000\000\000\000\000 \003\000\000\000\000\000\000\000\000\000\000\000\001\000\000\000\000\000\0002\000\000\000\000\000\000\000\304\000\320\301\220\000\000\\\000\000\000\000"
byte_size: 3276800

Registered Cuda shared memory with name 'input0_data'
```

It's important to notice that running with `docker-compose run triton-client python3 simple_grpc_cudashm_client.py --verbose also generates the same error.

## Attachments

**Script simple_grpc_cudashm_client.py**

```python
import os
import json
import sys
import argparse

import numpy as np
import tritonclient.grpc as grpcclient
from tritonclient import utils
import tritonclient.utils.cuda_shared_memory as cudashm

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('-v',
                        '--verbose',
                        action="store_true",
                        required=False,
                        default=False,
                        help='Enable verbose output')

     parser.add_argument('-u',
                        '--url',
                        type=str,
                        required=False,
                        default='localhost:8001',
                        help='Inference server URL. Default is localhost:8001.')

    FLAGS = parser.parse_args()

try:
        triton_client = grpcclient.InferenceServerClient(url=FLAGS.url,
                                                         verbose=FLAGS.verbose)
    except Exception as e:
        print("channel creation failed: " + str(e))
        sys.exit(1)


    triton_client.unregister_system_shared_memory()
    triton_client.unregister_cuda_shared_memory()

    model_name = "test"
    model_version = "latest"

    input_byte_size = 3276800 # 1600x512x4bytes
    output_byte_size = input_byte_size

    shm_op0_handle = cudashm.create_shared_memory_region(
        "output0_data", output_byte_size, 0)
    
    triton_client.register_cuda_shared_memory(
        "output0_data", cudashm.get_raw_handle(shm_op0_handle), 0,
        output_byte_size)
    
    shm_ip0_handle = cudashm.create_shared_memory_region(
        "input0_data", input_byte_size, 0)

    triton_client.register_cuda_shared_memory(
        "input0_data", cudashm.get_raw_handle(shm_ip0_handle), 0,
        input_byte_size)

```

Does anyone have an idea why this happens when launching the triton-client with docker-compose up? 

Thanks

**Comment by CoderHam** [comment]
@PauloFavero can you confirm your docker was run with necessary permissions to allow access of GPU?

**Comment by PauloFavero** [comment]
Hi @CoderHam 

Yes, I do have permission to access the GPU. The server for example is totally capable of loading the models, for example. If I didn't have permissions to access the GPU from the container, launching the script with `docker-compose run triton-client bash` wouldn't work

**Comment by CoderHam** [comment]
Your `docker-compose.yml` does not list the `--gpus` flag. Why do you think it has gpu access?
Can you try to create a cuda shared memory region outside of Triton or run nvidia-smi inside the container?

**Comment by PauloFavero** [comment]
> Your `docker-compose.yml` does not list the `--gpus` flag. Why do you think it has gpu access? Can you try to create a cuda shared memory region outside of Triton or run nvidia-smi inside the container?

Yes, I can run nvidia-smi inside the containers. I don't need the flag --gpus inside the compose when the `runtime: nvidia` is specified.

**Comment by PauloFavero** [comment]
I also upgraded the docker-compose version in order to change the how to configure the GPU in the compose.

```yml
version: '3.0'

services:
  triton-server:
    container_name: triton-server
    image: nvcr.io/nvidia/tritonserver:21.03-py3
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    shm_size: '2gb'
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    ipc: host
    ulimits:
      stack: 67108864
      memlock: -1
    environment:
      - LD_PRELOAD=/plugins/liblayerplugin.so
      - log-verbose=4
    command: bash -c "tritonserver --model-repository=/models --strict-model-config=false --grpc-infer-allocation-pool-size=16"

  triton-client:
    container_name: triton-client
    build:
      context: .
    network_mode: 'host'
    working_dir: /app/src
    depends_on:
      - triton-server
    environment:
      - log-verbose=4
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    network_mode: 'host'
    shm_size: '2gb'
    command: bash -c "python3 simple_grpc_cudashm_client_unilever.py --verbose"
```

Docker version: 20.10.8, build 3967b7d
docker-compose version: 1.29.2, build 5becea4c
Nvidia-SMI: 
```bash
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.57.02    Driver Version: 470.57.02    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:01:00.0  On |                  N/A |
| N/A   55C    P0    28W /  N/A |   1828MiB /  5926MiB |      1%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```

**Comment by PauloFavero** [comment]
Any update on this?

**Comment by PauloFavero** [comment]
Hi @tanmayv25 

Did you have any time to investigate this issue?

**Comment by tanmayv25** [comment]
We haven't had many cycles to work on the issue.. I will bump up the priority and keep posted about the updates.

**Comment by FCollaPi** [comment]
I am running into the same issue using  nvcr.io/nvidia/tritonserver   21.09-py3-sdk  for client and nvcr.io/nvidia/tritonserver 21.09-tf2-python-py3 for server, either running with docker CLI or docker-compose

**Comment by PauloFavero** [comment]
I tried using docker run instead of docker-compose but I got the same error.

`docker run --gpus all --rm -t --name triton-client --workdir=/app/src --network host --privileged --shm-size=2gb -v $(pwd)/project:/app  python3 simple_grpc_cudashm_client_unilever.py --verbose `

```unregister_system_shared_memory, metadata ()

Unregistered all system shared memory regions
unregister_cuda_shared_memory, metadata ()

Unregistered all cuda shared memory regions
register_cuda_shared_memory, metadata ()
name: "output0_data"
raw_handle: "\240\232;\002\000\000\000\000\001\000\000\000\000\000\000\000\000\0002\000\000\000\000\000 \003\000\000\000\000\000\000\000\000\000\000\000\001\000\000\000\000\000\0001\000\000\000\000\000\000\000\237\000\320\301\216\000\000\\\000\000\000\000"
byte_size: 3276800

Traceback (most recent call last):
  File "simple_grpc_cudashm_client.py", line 64, in <module>
    triton_client.register_cuda_shared_memory(
  File "/usr/local/lib/python3.8/dist-packages/tritonclient/grpc/__init__.py", line 984, in register_cuda_shared_memory
    raise_error_grpc(rpc_error)
  File "/usr/local/lib/python3.8/dist-packages/tritonclient/grpc/__init__.py", line 62, in raise_error_grpc
    raise get_error_grpc(rpc_error) from None
tritonclient.utils.InferenceServerException: [StatusCode.INVALID_ARGUMENT] failed to register CUDA shared memory region 'output0_data'
ERROR: 1 ```

**Comment by CoderHam** [comment]
@FCollaPi @PauloFavero we will work on a repro and a subsequent fix for the same.

**Comment by PauloFavero** [comment]
is there any progress on this issue? Is there a workaround for the moment?

**Comment by CoderHam** [comment]
@PauloFavero @FCollaPi I am unable to reproduce this issue. Can you provide me with additional environment information? As you can see the issue is occurring with registering the cuda shared memory in Triton and not with the creation / allocation of the cuda shared memory (`create_shared_memory_region`)

**Comment by PauloFavero** [comment]
Hi @CoderHam 

Thanks for giving a look into this issue. 
What kind of information do you need?

I tried with this [docker-compose.yml](https://github.com/triton-inference-server/server/issues/3429#issuecomment-933716254) and with simple_grpc example.

**Comment by rmccorm4** [comment]
Hi @PauloFavero ,

Can you reproduce this using the latest **22.03** containers? I just tried to follow your repro using `docker run` and was not able to repro. 

I also notice you're building a custom client container rather than using the SDK container directly. Can you try using the SDK container as-is?

```
# Start server container
docker run -ti --gpus all --network host -v $PWD:/mnt nvcr.io/nvidia/tritonserver:22.03-py3

# Start server inside container with "simple" models for cudashm client example
tritonserver --model-repository /mnt/server/docs/examples/model_repository --strict-
model-config=false --grpc-infer-allocation-pool-size=16

# Client (interative) - PASS
docker run -ti --gpus all --network host nvcr.io/nvidia/tritonserver:22.03-py3-sdk
ython3 /workspace/install/python/simple_grpc_cudashm_client.py

# Client (non-interactive) - PASS
docker run --gpus all --network host nvcr.io/nvidia/tritonserver:22.03-py3-sdk bash -c "python3 /workspace/install/python/simple_grpc_cudashm_client.py"
```

**Comment by rmccorm4** [comment]
Closing due to inactivity. Please re-open if you can easily reproduce with similar commands as above on the latest Triton version, I was unable to reproduce.

**Comment by msardonini** [comment]
I also have encountered this issue running the latest version of tritonserver `nvcr.io/nvidia/tritonserver:22.04-py3` and the tritonclient [2.21.0](https://pypi.org/project/tritonclient/#history) (installed from pip).

I've found that the issue only appears when the tritonclient is attempting to register memory from a process with PID == 1.

@rmccorm4 Try reproducing the issue using 'exec' in your command. That way, it will run in the calling process

`docker run --gpus all --network host nvcr.io/nvidia/tritonserver:22.03-py3-sdk exec bash -c "python3 /workspace/install/python/simple_grpc_cudashm_client.py"`

**Comment by rmccorm4** [comment]
Hi @msardonini ,

Can you elaborate or share an example I can copy/paste? I tried yours in (1) below but it failed.

1. Running your command as-is:
```
$ docker run --gpus all --network host nvcr.io/nvidia/tritonserver:22.03-py3-sdk exec bash -c "python3 /workspace/install/python/simple_grpc_cudashm_client.py"
...
/opt/nvidia/nvidia_entrypoint.sh: line 49: exec: exec: not found
```
2. Running `exec` in bash shell (non-interactive):
```
$ docker run --gpus all --network host nvcr.io/nvidia/tritonserver:22.03-py3-sdk bash -c "exec python3 /workspace/install/python/simple_grpc_cudashm_client.py"
# PASS: cudashm
```
3. Running with `exec` interactively:
```
# Start container interactively
$ docker run -ti --gpus all --network host nvcr.io/nvidia/tritonserver:22.03-py3-sdk

$ exec bash -c "python3 /workspace/install/python/simple_grpc_cudashm_client.py"
# PASS: cudashm

$ exec python3 /workspace/install/python/simple_grpc_cudashm_client.py
# PASS: cudashm
```
4. Using `docker exec`:
```
docker run -d -ti --name 2203sdk --gpus all --network host nvcr.io/nvidia/tritonserver:22.03-py3-sdk bash
docker exec 2203sdk python3 /workspace/install/python/simple_grpc_cudashm_client.py
# PASS: cudashm
```

**Comment by msardonini** [comment]
@rmccorm4 thanks for your quick reply!

The point was to run the simple_grpc_cudashm_client.py script in a process where PID == 1, so we can also do that by removing the `bash -c`

Can you try this command instead?

`docker run --gpus all --network host nvcr.io/nvidia/tritonserver:22.03-py3-sdk python3 /workspace/install/python/simple_grpc_cudashm_client.py`

Apologies the first example didn't work,

**Comment by rmccorm4** [comment]
Hi @msardonini ,

That still works for me:
```
$ docker run --gpus all --network host nvcr.io/nvidia/tritonserver:22.03-py3-sdk python3 /workspace/install/python/simple_grpc_cudashm_client.py
...
PASS: cudashm
```

I also tried checking some PIDs for sanity:
```
# pid1.sh

#!/bin/bash
python3 /workspace/install/python/simple_grpc_cudashm_client.py &
echo "Python PID: $! | Parent PID: $$ | RetCode: $?"
```
Output:
```
$ docker run --gpus all --network host -v $PWD:/mnt nvcr.io/nvidia/tritonserver:22.03-py3-sdk /mnt/pid1.sh
...
Python PID: 85 | Parent PID: 1 | RetCode: 0
```

**Comment by msardonini** [comment]
@rmccorm4 Bummer, that change made it fail for me, though my setup is slightly different. The only thing preventing me from replicating your setup exactly is the "simple" model. Is there somewhere I can download this? Then I could try and replicate the problem using these commands exactly.

**Comment by rmccorm4** [comment]
@msardonini sure, the you can find the [simple](https://github.com/triton-inference-server/server/tree/main/docs/examples/model_repository/simple) model in our example model repository. You can just clone the server repo and remove the rest of the directories other than `simple` in `server/docs/examples/model_repoistory` for the sake of this test. 

Note if you don't do that, the `inception_graphdef` and `densenet_onnx` directories are incomplete by default (large model files), so Triton will fail to load them unless you also run the [fetch_models.sh](https://github.com/triton-inference-server/server/blob/main/docs/examples/fetch_models.sh) to download their model files.

**Comment by msardonini** [comment]
Hi @rmccorm4 

I've been able to reproduce this issue using the 'simple' model, running the docker image `nvcr.io/nvidia/tritonserver:22.04-py3`. It happens when I run both the server and client in non-interactive mode.

To reproduce, cd to `server/docs/examples/model_repository`

### Start the triton-server
```
docker run --gpus all --network host -v $PWD:/mnt nvcr.io/nvidia/tritonserver:22.04-py3 tritonserver --model-repository /mnt
```

### Start the triton-client test
```
docker run --gpus all --network host nvcr.io/nvidia/tritonserver:22.04-py3-sdk python3 /workspace/install/python/simple_grpc_cudashm_client.py
```
This fails with the error message:
```
Traceback (most recent call last):
  File "/workspace/install/python/simple_grpc_cudashm_client.py", line 93, in <module>
    triton_client.register_cuda_shared_memory(
  File "/usr/local/lib/python3.8/dist-packages/tritonclient/grpc/__init__.py", line 1133, in register_cuda_shared_memory
    raise_error_grpc(rpc_error)
  File "/usr/local/lib/python3.8/dist-packages/tritonclient/grpc/__init__.py", line 62, in raise_error_grpc
    raise get_error_grpc(rpc_error) from None
tritonclient.utils.InferenceServerException: [StatusCode.INVALID_ARGUMENT] failed to register CUDA shared memory region 'output0_data'
``` 

If I start either the server or the triton client in interactive mode, the test passes. For example, I could start the server like this:
```
docker run -ti --gpus all --network host -v $PWD:/mnt nvcr.io/nvidia/tritonserver:22.04-py3

# Now in docker container
root@<NAME>:/opt/tritonserver# tritonserver --model-repository=/mnt

```

I have verified this behavior using two machines I am working with.

If it helps, here's my configuration:
nvidia driver: `NVIDIA-SMI 510.73.08    Driver Version: 510.73.08    CUDA Version: 11.6`
nvidia-docker2: 2.10.0-1
OS: Ubuntu20.04

**Comment by msardonini** [comment]
Hi @rmccorm4 and @Tabrizian ,

Any update on this topic? CUDA shmem provides a great performance improvement that I would like to enable again

**Comment by msardonini** [comment]
Hi @Tabrizian,

Unfortunately that didn't help. I added it to both server and client, and got the same error

**Comment by avraham-634** [comment]
Hello.
We also experiencing the same issue here.
Any idea on when we will have some kind of resolution here?

**Comment by Tabrizian** [comment]
I was able to root cause this issue. It looks like the problem is that `cudaIpcOpenMemHandle` will return invalid context if the handle’s source PID matches the destination process PID. When using Docker, the process ID namespace of both of the container is enabled which will allow reuse of the process IDs. When the interactive mode is used, the PIDs will be different and there will be no issues.

The fix would be to add `--pid host` flag to both of the containers. I was able to reproduce the issue locally and confirm that adding the flag fixes the issue.

**Comment by avraham-634** [comment]
Hi Iman.

Thank you very much on your support in resolving this issue.

Much appreciated!

[Logo  Description automatically generated]
Avraham Mahfuda
Computer Vision engineer

Afek 6, Kfar Saba
***@***.******@***.***>
www.634.ai<http://www.634.ai/>

**Comment by Tabrizian** [comment]
Closing the issue. Feel free to reopen if it is still not resolved.

**Comment by lminer** [comment]
@Tabrizian  In sagemaker, there's no ability to control the flags sent to your Docker image when it is run. Is there any alternate solution to this problem?

**Comment by SCraenen** [comment]
I'm running triton server nvcr.io/nvidia/tritonserver:23.04-py3 and nvcr.io/nvidia/tritonserver:23.04-py3-sdk as docker containers from my windows machine. I'm trying to run the simple_grpc_cudashm_client.py and I get this error:

```
Traceback (most recent call last):
  File "yolov7/simple_grpc_cudashm_client.py", line 88, in <module>
    triton_client.register_cuda_shared_memory(
  File "/usr/local/lib/python3.8/dist-packages/tritonclient/grpc/__init__.py", line 1300, in register_cuda_shared_memory
    raise_error_grpc(rpc_error)
  File "/usr/local/lib/python3.8/dist-packages/tritonclient/grpc/__init__.py", line 75, in raise_error_grpc
    raise get_error_grpc(rpc_error) from None
tritonclient.utils.InferenceServerException: [StatusCode.INVALID_ARGUMENT] failed to register CUDA shared memory region 'output0_data': failed to open CUDA IPC handle: invalid resource handle
```

I haven't changed any of the code. Here are my docker startup commands:

```
docker run --gpus all --rm --ipc=host --pid=host --shm-size=1g --ulimit memlock=-1 --ulimit stack=67108864 -p8000:8000 -p8001:8001 -p8002:8002 -v C:\Users\media\Documents\models\triton-model-repository:/models nvcr.io/nvidia/tritonserver:23.04-py3 tritonserver --model-repository=/models --log-verbose 5
```
```
docker run -it --rm -v C:\Users\media\Documents\triton-inference:/code --gpus all nvcr.io/nvidia/tritonserver:23.04-py3-sdk
```

The server has the simple model as ready.

Any help would be appreciated.

**Comment by Tabrizian** [comment]
CUDA IPC is not supported on Windows.

**Comment by Tabrizian** [comment]
@lminer Sorry this message must've fallen through the cracks. @nskool Are you aware of anyway to pass Docker flags in SageMaker?

**Comment by Davidnet** [comment]
Hi @Tabrizian I am able to reproduce this, even with the server and client having the `--ipc host

```bash 
docker run --gpus all --ipc host --network host -v $PWD:/mnt nvcr.io/nvidia/tritonserver:22.04-py3 tritonserver --model-repository /mnt
```
client

```
docker run --gpus all --ipc host --network host nvcr.io/nvidia/tritonserver:22.04-py3-sdk python3 /workspace/install/python/simple_grpc_cudashm_client.py
```

even though I have the last versions of the drivers and docker, my os UBUNTU 18.04.

I suspect something along the lines of cgroups, but would you mind sharing @Tabrizian what tools or method were you able to debug this?

I have looked at `journalctl -f` and `dmesg` and no issue whatsover. Any hand?

**Comment by Tabrizian** [comment]
@Davidnet you need to provide the `--pid host` flag as well.

**Comment by Tabrizian** [comment]
@SCraenen It may function but we don't officially test for those scenarios so there might be some hiccups.

**Comment by G-r-ay** [comment]
```
  triton-server:
    container_name: triton-server
    image: nvcr.io/nvidia/tritonserver:25.04-py3
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    volumes:
      - /models:/models
      - ./logs:/logs
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    ipc: host
    pid: host
    shm_size: 2g
    command: ["tritonserver","--log-file=/logs/server_logs.log", "--strict-readiness=true", "--model-control-mode=explicit", "--load-model=*", "--model-repository=/models"]


  orchestrator:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    ipc: host
    pid: host
    depends_on:
      - triton-server
    environment:
      - REDIS_HOST=redis-server
      - REDIS_PORT=6379
      - TRITON_URL=triton-server:8001
    command: ["sh", "-c", "python -m server.orchestrator || tail -f /dev/null"]

```

I just want to confirm if this issue is fully resolved. I know it works in interactive mode, but it still fails in Docker Compose even with `pid` and `ipc` set to `host`.

error:
```
orchestrator-1  |     self._register_shared_memory(worker_id)
orchestrator-1  |   File "/server/server/scripts/triton_inference_client.py", line 127, in _register_shared_memory
orchestrator-1  |     input_shm = cuda_shared_memory.create_shared_memory_region(input_name, self.input_total_size, self.config.gpu_device)
orchestrator-1  |   File "/opt/conda/lib/python3.10/site-packages/tritonclient/utils/cuda_shared_memory/__init__.py", line 140, in create_shared_memory_region
orchestrator-1  |     raise CudaSharedMemoryException(
orchestrator-1  | tritonclient.utils.cuda_shared_memory._utils.CudaSharedMemoryException: unable to create cuda shared memory handle
```
