### ISSUE TITLE
MIG deployment of triton gives error on GKE

### ISSUE THREAD

**Issue by swapkh91** [triton-inference-server/server#3506]
I'm trying to deploy triton server using MIG on GKE. I was able to run [this](https://cloud.google.com/kubernetes-engine/docs/how-to/gpus-multi) GKE example meaning MIG is working fine on the cluster.

Then I tried to deploy triton, but got the below error:
```
=============================
== Triton Inference Server ==
=============================

NVIDIA Release 21.07 (build 24810355)

Copyright (c) 2018-2021, NVIDIA CORPORATION & AFFILIATES.  All rights reserved.

Various files include modifications (c) NVIDIA CORPORATION.  All rights reserved.

This container image and its contents are governed by the NVIDIA Deep Learning Container License.
By pulling and using the container, you accept the terms and conditions of this license:
https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license

NOTE: Legacy NVIDIA Driver detected.  Compatibility mode ENABLED.

terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_S_construct null not valid
```

This is my yaml:
```
apiVersion: "serving.kubeflow.org/v1beta1"
kind: "InferenceService"
metadata:
  name: "triton-mms"
spec:
  predictor:
    nodeSelector:
      cloud.google.com/gke-gpu-partition-size: 1g.5gb
    triton:
      storageUri: <model_repo>
      imagePullPolicy: IfNotPresent
      args:
      - --allow-sagemaker=false
      runtimeVersion: 21.07-py3
      resources:
        limits:
          nvidia.com/gpu: 1
```

config.pbtxt
```
name: "test"
platform: "onnxruntime_onnx"
max_batch_size : 0
input [
  {
    name: "input"
    data_type: TYPE_FP32
    dims: [3,750,1333]
  }
]
output [
  {name: "3036"
    data_type: TYPE_FP32
    dims: [-1,4] #Expected batch size in output file
   },
    {
    name: "3044"
    data_type: TYPE_INT64
    dims: [-1] #Expected batch size in output file
   },
   {
    name: "3040"
    data_type: TYPE_FP32
    dims: [-1] #Expected batch size in output file
   },
{
    name: "2732"
    data_type: TYPE_INT64
    dims: [2] #Expected batch size in output file
   }
]
instance_group [
  {
    kind: KIND_GPU
    count: 1
  }
]
```

This model works fine without MIG on 1 whole GPU
