### ISSUE TITLE
S3 sync unloading all the models in triton

### ISSUE THREAD

**Issue by MeghaVarshney21** [triton-inference-server/server#3733]
I have created a github actions for aws s3 bucket. The yaml files looks like this:-

```
name: Deploy to Amazon S3

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1              

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
        
    - name: sync to s3
      run: aws s3 sync ./models s3://[bucket-name]
```

The command I am using to run the triton server is given below:-
```
"sudo docker run --restart unless-stopped -it -p 8000:8000 -p 8001:8001 -p 8002:8002 -e AWS_DEFAULT_REGION=us-east-1 -e AWS_ACCESS_KEY_ID=${aws_access_key} -e AWS_SECRET_ACCESS_KEY=${aws_secret_access_key} --shm-size 12G --gpus all --name triton_server tritonserver:21_12_v2 tritonserver --model-repository=s3://[bucket-name] --model-control-mode=poll --repository-poll-secs 120"
```

When I am running the github actions, it is unloading all the models on the triton server but it doesn't throw any error.
I am trying to automate the deployment of github model repo to the triton server.
Why it is unloading all the models?
