### ISSUE TITLE
Read-only file system error

### ISSUE THREAD

**Issue by Phelan164** [triton-inference-server/server#3744]
**Description**
Deploy Triton Python Backend into kubenetes with kserve and could not load the model

**Triton Information**
What version of Triton are you using?
Both Triton server 21.11-py3 and 21.12-py3 

Are you using the Triton container or did you build it yourself?
Using the Triton container, checked with both 21.11-py3 and 21.12-py3 

**To Reproduce**
Steps to reproduce the behavior.
- Deploy Triton server into kubenetes with kserve

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).
Python backend model with config:
```
name: "c64j84d9481ag524juu0"
backend: "python"
max_batch_size: 1024
input [
  {
    name: "input"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]
output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [ 3, 224, 224 ]
  }
]
instance_group [
  {
    count: 1
    kind: KIND_CPU
  }
]
dynamic_batching { }
version_policy: { all { }}
```

**Expected behavior**
Model load successfully

Note: model load successfully when run triton docker instead of kubenetes with kserve

Detail logging
<img width="1399" alt="Screen Shot 2021-12-29 at 14 38 38" src="https://user-images.githubusercontent.com/2509508/147640940-6d8525d1-867c-490d-a6bb-67ef70a98e92.png">

**Comment by Tabrizian** [comment]
Is the file system available in the container read-only? The `/dev/shm` path must be writable.

**Comment by Phelan164** [comment]
@Tabrizian I already made readOnly=False 
    ```
containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
          readOnly: false
```
