### ISSUE TITLE
Memory not released 

### ISSUE THREAD

**Issue by TannedCung** [triton-inference-server/server#3997]
**Description**
i do a stress inference into tritonserver. When i increase the load rate, tritonserver increases the memory consumed as well (to a certain level if i stop rising load rate). However, after i stop sending requests to triton, the memory is not released. With the small rate of request this doesn't happen.

**Triton Information**
Image: `nvcr.io/nvidia/tritonserver:22.01-py3` and `nvcr.io/nvidia/tritonserver:21.04-py3` without GPU
CPU: i7 10400F (i limit triton to use 4 cpus of this)
Memory: 32GB  (limit to 5GB)
Model: OpenVINO [emotions.zip](https://github.com/triton-inference-server/server/files/8159891/emotions.zip)

Are you using the Triton container or did you build it yourself: image from docker hub

**To Reproduce**
Here are the command in docker-compose
```
face_triton:
    image: nvcr.io/nvidia/tritonserver:22.01-py3
    ports:
      - 8000:8000
      - 8001:8001
      - 8002:8002
    ulimits:
      rtprio: 95
      memlock: -1

    command: [ tritonserver, --model-repository, /models, --log-verbose, "1" ]
    volumes:
      - /models:/models
    environment:
      - NVIDIA_VISIBLE_DEVICES=None
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 5G
```

**Expected behavior**
Triton released the RAM after a while
