### ISSUE TITLE
Endless wait when loading Python backend model on Jetson - v2.19.0

### ISSUE THREAD

**Issue by KarelvdVrie** [triton-inference-server/server#4113]
**Description**
Using the TRITON 2.19.0 server build into an image docker for the Jetson TX2 with the `add_sub` Python model makes the server hang forever when loading the model. The TensorRT, ONNX, and Tensorflow backends do load their models.
The TRITON does not give an error but the following is the output log:
```
triton-server  | I0325 11:25:44.774643 1 shared_library.cc:108] OpenLibraryHandle: /Workdir/TRITON/backends/pytorch/libtriton_pytorch.so
triton-server  | I0325 11:25:44.777248 1 triton_backend_manager.cc:101] unloading backend 'pytorch'
triton-server  | I0325 11:25:44.895887 1 pinned_memory_manager.cc:240] Pinned memory pool is created at '0x101070000' with size 268435456
triton-server  | I0325 11:25:44.896137 1 cuda_memory_manager.cc:105] CUDA memory pool is created on device 0 with size 67108864
triton-server  | I0325 11:25:44.906950 1 model_config_utils.cc:667] Server side auto-completed config: name: "add_sub"
triton-server  | input {
triton-server  |   name: "INPUT0"
triton-server  |   data_type: TYPE_FP32
triton-server  |   dims: 4
triton-server  | }
triton-server  | input {
triton-server  |   name: "INPUT1"
triton-server  |   data_type: TYPE_FP32
triton-server  |   dims: 4
triton-server  | }
triton-server  | output {
triton-server  |   name: "OUTPUT0"
triton-server  |   data_type: TYPE_FP32
triton-server  |   dims: 4
triton-server  | }
triton-server  | output {
triton-server  |   name: "OUTPUT1"
triton-server  |   data_type: TYPE_FP32
triton-server  |   dims: 4
triton-server  | }
triton-server  | instance_group {
triton-server  |   kind: KIND_CPU
triton-server  | }
triton-server  | backend: "python"
triton-server  | 
triton-server  | I0325 11:25:44.907182 1 model_repository_manager.cc:700] AsyncLoad() 'add_sub'
triton-server  | I0325 11:25:44.907307 1 model_repository_manager.cc:939] TriggerNextAction() 'add_sub' version 1: 1
triton-server  | I0325 11:25:44.907370 1 model_repository_manager.cc:975] Load() 'add_sub' version 1
triton-server  | I0325 11:25:44.907384 1 model_repository_manager.cc:994] loading: add_sub:1
triton-server  | I0325 11:25:45.008071 1 model_repository_manager.cc:1052] CreateModel() 'add_sub' version 1
triton-server  | I0325 11:25:45.008675 1 shared_library.cc:108] OpenLibraryHandle: /Workdir/TRITON/backends/python/libtriton_python.so
triton-server  | I0325 11:25:45.019121 1 python.cc:1684] 'python' TRITONBACKEND API version: 1.8
triton-server  | I0325 11:25:45.019217 1 python.cc:1703] backend configuration:
triton-server  | {}
triton-server  | I0325 11:25:45.019271 1 python.cc:1819] Shared memory configuration is shm-default-byte-size=67108864,shm-growth-byte-size=67108864,stub-timeout-seconds=30
triton-server  | I0325 11:25:45.022821 1 python.cc:1859] TRITONBACKEND_ModelInitialize: add_sub (version 1)
triton-server  | I0325 11:25:45.026011 1 model_config_utils.cc:1616] ModelConfig 64-bit fields:
triton-server  | I0325 11:25:45.026120 1 model_config_utils.cc:1618]    ModelConfig::dynamic_batching::default_queue_policy::default_timeout_microseconds
triton-server  | I0325 11:25:45.026151 1 model_config_utils.cc:1618]    ModelConfig::dynamic_batching::max_queue_delay_microseconds
triton-server  | I0325 11:25:45.026168 1 model_config_utils.cc:1618]    ModelConfig::dynamic_batching::priority_queue_policy::value::default_timeout_microseconds
triton-server  | I0325 11:25:45.026193 1 model_config_utils.cc:1618]    ModelConfig::ensemble_scheduling::step::model_version
triton-server  | I0325 11:25:45.026211 1 model_config_utils.cc:1618]    ModelConfig::input::dims
triton-server  | I0325 11:25:45.026227 1 model_config_utils.cc:1618]    ModelConfig::input::reshape::shape
triton-server  | I0325 11:25:45.026243 1 model_config_utils.cc:1618]    ModelConfig::instance_group::secondary_devices::device_id
triton-server  | I0325 11:25:45.026265 1 model_config_utils.cc:1618]    ModelConfig::model_warmup::inputs::value::dims
triton-server  | I0325 11:25:45.026281 1 model_config_utils.cc:1618]    ModelConfig::optimization::cuda::graph_spec::graph_lower_bound::input::value::dim
triton-server  | I0325 11:25:45.026296 1 model_config_utils.cc:1618]    ModelConfig::optimization::cuda::graph_spec::input::value::dim
triton-server  | I0325 11:25:45.026311 1 model_config_utils.cc:1618]    ModelConfig::output::dims
triton-server  | I0325 11:25:45.026334 1 model_config_utils.cc:1618]    ModelConfig::output::reshape::shape
triton-server  | I0325 11:25:45.026352 1 model_config_utils.cc:1618]    ModelConfig::sequence_batching::direct::max_queue_delay_microseconds
triton-server  | I0325 11:25:45.026368 1 model_config_utils.cc:1618]    ModelConfig::sequence_batching::max_sequence_idle_microseconds
triton-server  | I0325 11:25:45.026383 1 model_config_utils.cc:1618]    ModelConfig::sequence_batching::oldest::max_queue_delay_microseconds
triton-server  | I0325 11:25:45.026398 1 model_config_utils.cc:1618]    ModelConfig::sequence_batching::state::dims
triton-server  | I0325 11:25:45.026413 1 model_config_utils.cc:1618]    ModelConfig::sequence_batching::state::initial_state::dims
triton-server  | I0325 11:25:45.026429 1 model_config_utils.cc:1618]    ModelConfig::version_policy::specific::versions
triton-server  | I0325 11:25:45.027675 1 python.cc:1908] TRITONBACKEND_ModelInstanceInitialize: add_sub_0 (CPU device 0)
triton-server  | I0325 11:25:45.027749 1 backend_model_instance.cc:72] Creating instance add_sub_0 on CPU using artifact ''
triton-server  | I0325 11:25:45.053005 9 python.cc:1209] Starting Python backend stub:  exec /Workdir/TRITON/backends/python/triton_python_backend_stub /Workdir/Models/add_sub/1/model.py triton_python_backend_shm_region_1 67108864 67108864 1 /Workdir/TRITON/backends/python 64 add_sub_0
```
There does not seem to be any system load during the time it is waiting, no growth of memory usage either.

**Triton Information**
I build a container for the 2.19.0 TRITON server using the prebuild server tar using the following Dockerfile:

```
FROM nvcr.io/nvidia/nvidia-l4t-base:r32.7.1

ENV JETPACK_VERSION=4.6.1
ENV TRITON_VERSION=2.19.0
ENV TRITON_PATH=/Workdir/TRITON/

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update              \
        && apt-get install -y --no-install-recommends \
        libb64-0d               \
        libre2-4                \
        libssl1.1               \
        rapidjson-dev           \
        libopenblas-dev         \
        libarchive-dev          \
        zlib1g                  \
        python3                 \
        python3-dev             \
        python3-pip

RUN python3 -m pip install -U pip setuptools
RUN python3 -m pip install numpy

WORKDIR ${TRITON_PATH}/

RUN wget https://github.com/triton-inference-server/server/releases/download/v$TRITON_VERSION/tritonserver$TRITON_VERSION-jetpack$JETPACK_VERSION.tgz \
    && tar -xvf tritonserver$TRITON_VERSION-jetpack$JETPACK_VERSION.tgz \
    && ln -s ${TRITON_PATH}/bin/tritonserver /usr/bin/tritonserver \
    && rm tritonserver${TRITON_VERSION}-jetpack$JETPACK_VERSION.tgz

WORKDIR /Workdir/
```

**To Reproduce**
Using the above Dockerfile to build the image with the following docker-compose file to run the container:
```
  triton-server:
    image: triton-inference-server:2.19.0-aarch64-jetpack4.6
    container_name: triton-server
    ports:
      - 8000:8000
      - 8001:8001
      - 8002:8002
    runtime: nvidia
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - ./Models:/Workdir/Models
    environment:
      - "NVIDIA_VISIBLE_DEVICES=0"
      - "NVIDIA_DRIVER_CAPABILITIES=compute,graphics,utility,video"
    command: tritonserver --backend-directory=/Workdir/TRITON/backends --model-store=/Workdir/Models --strict-model-config=false --exit-on-error=true --log-verbose=true --model-control-mode=Explicit --load-model "add_sub"
```
The model + configuration can be found in the [examples directory of the Python backend](https://github.com/triton-inference-server/python_backend/tree/main/examples/add_sub). No modifications have been made to these files.

**Expected behavior**
I expect the model to load the same as it does on an AMD64 platform. I have not tested previous builds of the server because the standard packages did not include the Python backend yet. I hope this is enough information, if I can help please let me know.

**Comment by Tabrizian** [comment]
Do you have any other instances of Triton running in the background? Does the hang happen on every Triton start or this is an intermittent issue?

**Comment by KarelvdVrie** [comment]
No this is the only instance running, and the Jetson has been newly flashed with the latest software. And it happens on every start, I have tried with different python files and configurations, neither has helped.

**Comment by KarelvdVrie** [comment]
Running it without GPU access gives the same problem, which implies either something goes wrong in the build of the container or something is wrong with the Python backend, right? 
```
  triton-server:
    image: triton-inference-server:2.19.0-aarch64-jetpack4.6
    container_name: triton-server
    ports:
      - 8000:8000
      - 8001:8001
      - 8002:8002
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - ./Models:/Workdir/Models
    command: tritonserver --backend-directory=/Workdir/TRITON/backends --model-store=/Workdir/Models --strict-model-config=false --exit-on-error=true --log-verbose=true --model-control-mode=Explicit --load-model "add_sub"
```
Because this way the container is separated from the software such as CUDA and TensorRT of the Jetson? Or does the Nvidia-docker on Jetson still port through packages?
