### ISSUE TITLE
perf_analyzer socket closed error

### ISSUE THREAD

**Issue by shoval-a** [triton-inference-server/server#4378]
**Description**
I'm using perf_analyzer in order to measure the throughput of my model (TensorRT platform).
In addition, I'm using **Nginx** as a proxy to all pods which are running Triton. 

![nginx-triton](https://user-images.githubusercontent.com/75360180/168579955-abbe52fb-f830-4be6-a22e-b412fa90ead5.jpg)

Therefore my perf_analyzer command looks like this:
```bash
./perf_analyzer -m model -u MY-NGINX-BACKEND -i grpc -v --ssl-grpc-use-ssl true --ssl-grpc-root-certificate-file MY-CERT.crt 
--concurrency-range 1:4:1
```

and the output is:
```
Request concurrency: 1
  Pass [1] throughput: 56 infer/sec ...
  Pass [2] throughput: 56.5 infer/sec ...
  Pass [3] throughput: 56.8 infer/sec ...


Request concurrency: 2
  Pass [1] throughput: 103 infer/sec ...
  Pass [2] throughput: 103.2 infer/sec ...
  Pass [3] throughput: 78.6 infer/sec ...
Failed to maintain requested inference load. Worker thread(s) failed to generate concurrent requests.
Thread [0] had error: Socket closed
```

**IMPORTANT**
When I configure **perf_analyzer** to work via HTTP protocol, everything is fine!
I think it's the combination of gRPC protocol + Nginx + mechanism of perf_analyzer with concurrent requests. 

**Triton Information**
22.02-py3

**To Reproduce**
1. AKS (K8S version: 1.21)
2. tritonserver:22.02-py3
3. nginx ingress controller (v:1.2.0)

**Expected behavior**
I know for sure that its not a problem of my model, because until now I configure **perf_analyzer** to work directly to Kubernetes Service, and the results were pretty well.
Now, I wanted to add nginx into the architecture, and specifically with <ins> gRPC protocol and concurrency greater than 1 </ins> I'm dealing with Socket error issues. 

**Summary** 
1. perf_analyzer directly to Kubernetes Service works good with gRPC and HTTP.
2. perf_analyzer configured to nginx proxy with HTTP protocol works fine.
3. perf_analyzer configured to nginx proxy with gRPC + concurrency=1  - works fine.
4. perf_analyzer configured to nginx proxy with gRPC + concurrency greater than 1 - Socket Closed !

**Comment by krishung5** [comment]
Hi @shoval-a,thank you for filing this issue. Could you provide more information regarding how you are exporting gRPC endpoint via nginx? Meanwhile, we have filed a ticket to investigate further.

**Comment by shoval-a** [comment]
my `nginx` Ingress yaml file:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: GRPC
    nginx.ingress.kubernetes.io/grpc-read-timeout: "120s"
    nginx.ingress.kubernetes.io/grpc-send-timeout: "120s"
    nginx.ingress.kubernetes.io/large-client-header-buffers: "8k"
  name: triton-nginx
  namespace: triton
spec:
  rules:
    - host: my-triton-domain.com
      http:
        paths:
          - backend:
              service:
                name: triton-service
                port:
                  number: 8001
            path: /
            pathType: Prefix
    tls:
      - hosts:
        - my-triton-domain.com
      - sercretName: my-tls-secret
```

`perf_analyzer` communicate with `nginx` via `gRPC` and `nginx` should load balance its requests into the relevant pods via `gRPC` as well.
