### ISSUE TITLE
Using S3 repository for Triton does not working properly / Cannot plug in to S3

### ISSUE THREAD

**Issue by AkSino** [triton-inference-server/server#4689]
**Description**

Hello, I'm currently using Triton and I would like to deploy/use it for a local or private instance of S3 (Cloudian) but it can't connect to it.

```
I0725 07:46:16.201920 32 server.cc:247] No server context available. Exiting immediately.
error: creating server: Internal - Could not get MetaData for bucket with name s3-********* due to exception: , error message: curlCode: 28, Timeout was reached
```

**Triton Information**
What version of Triton are you using?

I'm using Triton 22.04

Are you using the Triton container or did you build it yourself?

Triton Container

**To Reproduce**
Steps to reproduce the behavior.

2 Ways

Deployment on Openshift:

deployment.yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flower-2
  labels:
    app: flower-2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flower-2
  template:
    metadata:
      labels:
        app: flower-2
    spec:
      containers:
        - name: flower-2
          ports:
          - containerPort: 8000
            name: http-triton
          - containerPort: 8001
            name: grpc-triton
          - containerPort: 8002
            name: metrics-triton
          image: "nvcr.io/nvidia/tritonserver:22.04-py3"
          command: ["/bin/sh", "-c"]
          args: ["tritonserver --model-repository=s3://s3-*********/df-triton --model-control-mode=poll"]
          env:
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: cloudian-credentials
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: cloudian-credentials
                key: AWS_SECRET_ACCESS_KEY
          resources:
            limits:
              memory: 4000Mi
```

Directly docker:

```
docker run --rm -p8400:8000 -p8401:8001 -p8402:8002 \
	-e AWS_ACCESS_KEY_ID=******** -e AWS_SECRET_ACCESS_KEY=******** nvcr.io/nvidia/tritonserver:22.04-py3 \
	tritonserver --model-repository=s3://s3-*********/df-triton
```

**Additional information**

Using the aws command I can connect to it in the following way:

```
aws --endpoint-url=http://s3-******** s3 ls df-triton/         
                                                                                                          
2022-07-19 15:49:47       1790 vision_classification_pj_2
```

**Expected behavior**
The server manages to plug in to S3 

Thanks
