### ISSUE TITLE
Triton pod not scheduled in all GPUs in a physical server.

### ISSUE THREAD

**Issue by shan100github** [triton-inference-server/server#4761]
**Description**
In the below hardware configuration, while trying to deploy NVIDIA triton service with 4 replicas in this server with 1 GPU each, 3 pods were running and the 4th pod was not spinning up and the following error was displayed.

```
FailedScheduling    pod/model-2-79d7d6786c-bprm8    0/1 nodes are available: 1 Insufficient nvidia.com/gpu, 1 node(s) had taint {protect: no_schedule}, that the pod didn't tolerate, 1 node(s) didn't match Pod's node affinity/selector.
```

Hardware - SYS-740GP-TNRT
Hardware - RTX A6000 x 4 GPUs
Hardware - Intel(R) Xeon(R) Gold 6326 CPU @ 2.90GHz
Operating System - Ubuntu 20.04
Kubernetes - RKE2 - v1.21.14+rke2r1

Deployment file used:
```
 apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: model-infr
spec:
  replicas: 4
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: model-infr
    spec:
      containers:
      - args:
        - pip3 install opencv-python-headless && tritonserver --model-store=s3://model-infr/
        command:
        - /bin/sh
        - -c
        image: nvcr.io/nvidia/tritonserver:22.06-py3
        imagePullPolicy: IfNotPresent
        name: tritonserver
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        - containerPort: 8001
          name: grpc
          protocol: TCP
        - containerPort: 8002
          name: metrics
          protocol: TCP
        resources:
          limits:
            nvidia.com/gpu: "1"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /dev/shm
          name: dshm
      dnsPolicy: ClusterFirst
      nodeSelector:
        nvidia.com/gpu.product: NVIDIA-RTX-A5000
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir:
          medium: Memory
        name: dshm
```

While checking nvidia-smi in the actual system was able to get below output and clearly denotes GPU0 was free to schedule.

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.54       Driver Version: 510.54       CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA RTX A5000    Off  | 00000000:31:00.0 Off |                  Off |
| 30%   46C    P8    22W / 230W |     10MiB / 24564MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA RTX A5000    Off  | 00000000:4B:00.0 Off |                  Off |
| 48%   76C    P2   149W / 230W |  13222MiB / 24564MiB |     29%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA RTX A5000    Off  | 00000000:B1:00.0 Off |                  Off |
| 52%   81C    P2   166W / 230W |  13222MiB / 24564MiB |     57%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  NVIDIA RTX A5000    Off  | 00000000:CA:00.0 Off |                  Off |
| 52%   80C    P2   176W / 230W |  13222MiB / 24564MiB |     66%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1580      G   /usr/lib/xorg/Xorg                  4MiB |
|    0   N/A  N/A      2231      G   /usr/lib/xorg/Xorg                  4MiB |
|    1   N/A  N/A      1580      G   /usr/lib/xorg/Xorg                  4MiB |
|    1   N/A  N/A      2231      G   /usr/lib/xorg/Xorg                  4MiB |
|    1   N/A  N/A    911402      C   tritonserver                    13209MiB |
|    2   N/A  N/A      1580      G   /usr/lib/xorg/Xorg                  4MiB |
|    2   N/A  N/A      2231      G   /usr/lib/xorg/Xorg                  4MiB |
|    2   N/A  N/A    911401      C   tritonserver                    13209MiB |
|    3   N/A  N/A      1580      G   /usr/lib/xorg/Xorg                  4MiB |
|    3   N/A  N/A      2231      G   /usr/lib/xorg/Xorg                  4MiB |
|    3   N/A  N/A    911223      C   tritonserver                    13209MiB |
+-----------------------------------------------------------------------------+
```

**Triton Information**
nvcr.io/nvidia/tritonserver:22.06-py3 as a container in the Kubernetes platform.

**Expected behavior**
Expecting Triton to schedule pods in all 4 GPUs.
