### ISSUE TITLE
Triton Inference Server Image Python Libraries

### ISSUE THREAD

**Issue by TrevorM15** [triton-inference-server/server#4998]
**Description**
I am trying to run code using CuPy, and this issue #4477 insinuates that it's installed in the image, but when I start the server it errors out saying `UNAVAILABLE: Internal: ModuleNotFoundError: No module named 'cupy'`. 

**Triton Information**
version: `22.07-py3`

**To Reproduce**
Code:
`model.py`

```python
import cupy
from cupyx.scipy import ndimage
import triton_python_backend_utils as pb_utils

class TritonPythonModel:
    """Your Python model must use the same class name. Every Python model
    that is created must have "TritonPythonModel" as the class name.
    """

    def execute(self, requests):

        responses = []

        # Every Python backend must iterate over everyone of the requests
        # and create a pb_utils.InferenceResponse for each of them.
        for request in requests:

            image = pb_utils.get_input_tensor_by_name(request, "image")
            image = cupy.from_dlpack(image.to_dlpack())
            filtered_image = ndimage.gaussian_filter(image, 1)               
            filtered_image = pb_utils.Tensor("filtered_image", filtered_image.astype(float))

            # Create InferenceResponse. You can set an error here in case
            # there was a problem with handling this inference request.
            # Below is an example of how you can set errors in inference
            # response:
            #
            # pb_utils.InferenceResponse(
            #    output_tensors=..., TritonError("An error occured"))
            inference_response = pb_utils.InferenceResponse(
                output_tensors=[filtered_image])
            responses.append(inference_response)

        # You should return a list of pb_utils.InferenceResponse. Length
        # of this list must match the length of `requests` list.
        return responses
```

`config.pbtxt`

```python
name: "gpu"
backend: "python"

input [
  {
    name: "image"
    data_type: TYPE_FP32
    dims: [ -1, -1 ]
  }
]
output [
  {
    name: "filtered_image"
    data_type: TYPE_FP32
    dims: [ -1, -1 ]
  }
]
```

**Expected behavior**
CuPy is installed in the image and the model loads successfully into the server.

**Comment by kthui** [comment]
Hi @TrevorM15, you can install CuPy into the image after you pull it, following [CuPy's installation guide](https://docs.cupy.dev/en/stable/install.html#installing-cupy). Another option is to use a [Custom Python Execution Environment](https://github.com/triton-inference-server/python_backend#using-custom-python-execution-environments), and install CuPy inside the environment.

**Comment by TrevorM15** [comment]
I got it to work for KServe. For posterity, here is some sample yaml:
```yaml
apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "model"
spec:
  predictor:
    triton:
      command: ["/bin/sh", "-c", "python3 -m pip install cupy"]
      runtimeVersion: 22.07-py3
      resources:
        limits:
          cpu: "1"
          memory: 2Gi
      storageUri: "gs://mymodel_bucket/models/triton/model"
```
