### ISSUE TITLE
USE GRPC ON OPENSHIFT

### ISSUE THREAD

**Issue by AkSino** [triton-inference-server/server#5018]
**Description**
Hello,

I try this, you never know maybe you already had this problem :)

I would like to deploy an inference server on Openshift and use the GRPC service. The problem is that I can not access it through ingress or routes.

Namely I do not work with Traefik, I would like to stay on Networking but maybe is not possible:
ingress.yaml
```yaml
kind: Ingress
apiVersion: networking.k8s.io/v1
```
Should I add something in particular in the annotations, type...

When building with docker locally and using grpcurl:

```bash
grpcurl -proto ./grpc_service.proto -plaintext 127.0.0.1:8001 inference.GRPCInferenceService/ServerReady -> "ready": true
```

But when I'm trying to request on Openshift:

```bash
grpcurl -proto ./grpc_service.proto -plaintext test-flower-2-dataia-ttech.enterprise:80 inference.GRPCInferenceService/ServerReady
ERROR:
  Code: Unavailable
  Message: unexpected HTTP status code received from server: 502 (Bad Gateway); transport: received unexpected content-type "text/html"
```
It works fine using HTTP, I just change the port in the ingress.

Thanks
**Triton Information**
What version of Triton are you using?
22.03

Are you using the Triton container or did you build it yourself?
Container

**To Reproduce**
Steps to reproduce the behavior.

I mainly use your [k8s On Prem](https://github.com/triton-inference-server/server/tree/main/deploy/k8s-onprem)

The following files are the ones I modified for my case:

I do not have **hpa.yaml**

**Chart.yaml**
```yaml
---
apiVersion: v2
name: flower
type: application
version: 0.0.1
```

**values.yaml**
```yaml
---
tags:
  autoscaling: true
  loadBalancing: true

env: recx

# Definition image
image:
  imageName: nvcr.io/nvidia/tritonserver:22.03-py3
  pullPolicy: IfNotPresent

limits:
  memory: 4000Mi

autoscaling:
  minReplicas: 1
  maxReplicas: 4
  metrics:
    - type: Pods
      pods:
        metric:
          name: avg_time_queue_us
        target:
          type: AverageValue
          averageValue: 50
```

**ingress.yaml**
```yaml
---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: 'rt-{{ template "triton-inference-server.fullname" . }}'
  labels:
    helm.sh/chart-name: "{{.Chart.Name }}"
    helm.sh/chart-version: "{{.Chart.Version }}"
spec:
  rules:
    - host: '{{ template "triton-inference-server.name" . }}.{{ .Values.env }}.{{- regexReplaceAll "-[^-]*$" .Release.Namespace "" -}}.enterprise'
      http:
        paths:
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: 'svc-{{ template "triton-inference-server.fullname" . }}'
              port:
                number: 8001
```

**deployment.yaml**
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "triton-inference-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "triton-inference-server.name" . }}
    chart: {{ template "triton-inference-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.autoscaling.minReplicas }}
  selector:
    matchLabels:
      app: {{ template "triton-inference-server.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "triton-inference-server.name" . }}
        release: {{ .Release.Name }}

    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.imageName }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          resources:
            limits:
              memory: {{.Values.limits.memory}}

          args: ["tritonserver", "--model-repository=/mnt --exit-on-error=false"]

          ports:
            - containerPort: 8000
              name: http
            - containerPort: 8001
              name: grpc
            - containerPort: 8002
              name: metrics
          livenessProbe:
            httpGet:
              path: /v2/health/live
              port: http
          readinessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            httpGet:
              path: /v2/health/ready
              port: http

```

**service.yaml**
```yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ template "triton-inference-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "triton-inference-server.name" . }}
    chart: {{ template "triton-inference-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  clusterIP: None
  ports:
    - port: 8000
      targetPort: http
      name: http-inference-server
    - port: 8001
      targetPort: grpc
      name: grpc-inference-server
    - port: 8002
      targetPort: metrics
      name: metrics-inference-server
  selector:
    app: {{ template "triton-inference-server.name" . }}
    release: {{ .Release.Name }}
```

**Expected behavior**
I can request my inference server
