### ISSUE TITLE
Proper input in json file, for python model accepting dictionary with string values as input

### ISSUE THREAD

**Issue by ApoorveK** [triton-inference-server/server#5308]
**Description**
Current "data.json' needed for yaml file for model analyzer doesn't work

**Triton Information**
What version of Triton are you using?
Latest version in master branch

Are you using the Triton container or did you build it yourself?
-> building from repo (i.e. using Model-analyzer:latest)

**To Reproduce**
For given json file containing input ->
```
{
    "data" :
     [
        {
          "input" : {
            "content" : {"text":"hi i am apoorve","speaker_name":"voice_B","language":"english","sample_rate":"16000","length":"0.7"},
            "shape" : [1,5]
          }
        }
      ]
  }
```
For following yaml file : 
```
model_repository: /models
run_config_search_max_instance_count: 16
run_config_search_max_concurrency: 72
collect_cpu_metrics: True
profile_models: 
  tts_phoneme_model:
    model_config_parameters:
      # max_batch_size: 4
      # dynamic_batching:
      instance_group:
        - - kind: KIND_GPU
            count: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]
    parameters:
      concurrency:
        start: 4
        stop: 72
        step: 4
      # batch_sizes:
      #   start: 2
      #   stop: 4
      #   step: 2

perf_analyzer_flags:
  percentile: 95
  shape:
     - input:1,5
  input-data: stressTestData.json
```

Python model takes dictionary as input. Model is being initialised properly  in triton repository, but while using 'Model Analyzer' following error comes :->
11:26:10 [Model Analyzer] Running perf_analyzer failed with exit status 99:
error: Failed to init manager inputs: The tensor values are not supported. Expected an array or b64 string ( Location stream id: 0, step id: 0)

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

**Expected behavior**
Starts model analyzer properly without any issues.
