### ISSUE TITLE
Server is returning BYTES when output datatype is FP32

### ISSUE THREAD

**Issue by gotofbi** [triton-inference-server/server#5484]
Hi, I am having issue with inferencing onnx model with triton.

```yaml
name: "custom_onnx"
platform: "onnxruntime_onnx"
max_batch_size : 0
input [
  {
    name: "input"
    data_type: TYPE_FP32
    format: FORMAT_NCHW
    dims: [ 3, 64, 216 ]
    reshape { shape: [ 1, 3, 64, 216 ] }
  }
]
output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [ 1, 8, 833 ]
  }
]

```

And I slightly modified image_client.py to able to ignore `Exception("expecting model output to be a vector")`

`python3.8 image_client.py -i grpc -u localhost:8001 -m custom_onnx image.jpg`

and response is like this

```shell
Namespace(async_set=False, batch_size=1, classes=1, image_filename='image.jpg', model_name='custom_onnx', model_version='', protocol='grpc', scaling='NONE', streaming=False, url='localhost:8001', verbose=False)

model_name: "custom_onnx"
model_version: "1"
id: "1"
outputs {
  name: "output"
  datatype: "BYTES"
  shape: 1
}
raw_output_contents: "\016\000\000\00033.569187:5831"
```

I would expect output datatype as "FP32" but somehow its returning BYTES

When I test same onnx file with onnxruntime, I get this result

Code
```python
    ort_sess = ort.InferenceSession(MODEL_FN)
    input_tensor = ort_sess.get_inputs()[0]

    img = Image.open(io.BytesIO(image_file))

    img = np.array(img)
    img = img.astype(np.float32) / 255.0
    img = (img - 0.5) / 0.5
    img = np.transpose(img, (2, 0, 1))
    img = np.expand_dims(img, axis=0)

    outputs = ort_sess.run(None, {input_tensor.name: img})
    print(outputs)
    selected_indices = np.argmax(outputs, axis=-1)
    print(selected_indices)

```
Result
```shell
[array([[[ 3.1983364e+00,  1.5812457e+01,  2.0996990e+01, ...,
         -1.1771901e-01, -6.4978571e+00, -4.0233669e+00],
        [ 3.8350031e+00, -9.2549028e+00,  6.6624165e+00, ...,
          1.4210399e+00,  1.3134724e+00,  1.4243821e+00],
        [ 4.8365297e+00,  2.1208582e+00,  3.1010940e+00, ...,
          2.0299879e+01,  4.4024148e+00,  5.7284374e+00],
        ...,
        [ 2.2264168e+01, -1.9038075e+00, -7.8751606e-01, ...,
          1.9645711e+00,  1.3015848e+00,  2.3283694e+00],
        [ 2.4436743e+01,  1.2383875e+00,  2.2391722e+00, ...,
          2.7818110e+00, -8.1663787e-01,  8.7072480e-01],
        [ 3.1089619e+01,  1.6684982e+00,  2.3435636e-01, ...,
         -3.1817090e-03,  6.1054593e-01,  7.5442380e-01]]], dtype=float32)]
[[[  9 222 779  74 143   0   0   0]]]
```

What am I missing?
