### ISSUE TITLE
No space left on device on when deployed using python backend

### ISSUE THREAD

**Issue by DimasAdinugroho** [triton-inference-server/server#5868]
**Description**
I tried to deploy a triton (using version: 23.01) ensemble model with python backend and custom backend stub (conda env). It running fine on local (using docker), but when I tried to run on kubernetes cluster it return errors. Tried to spawn on other nodes and also change the `model-repository` but no luck, it still return the same.

```
 <frozen importlib._bootstrap>(991): _find_and_load
  /models/blur_classification/1/model.py(6): <module>
  <frozen importlib._bootstrap>(219): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(843): exec_module
  <frozen importlib._bootstrap>(686): _load_unlocked
  <frozen importlib._bootstrap>(975): _find_and_load_unlocked
  <frozen importlib._bootstrap>(991): _find_and_load
I0529 10:21:51.291749 1 model_lifecycle.cc:694] successfully loaded 'preprocess' version 1
E0529 10:21:51.291878 1 model_repository_manager.cc:487] Invalid argument: ensemble 'triton' depends on 'blur_classification' which has no loaded version. Model 'blur_classification' loading failed with error: version 1 is at UNAVAILABLE state: Internal: OSError: [Errno 28] No space left on device
At:
  /tmp/python_env_83tkOi/0/lib/python3.8/multiprocessing/synchronize.py(61): __init__
  /tmp/python_env_83tkOi/0/lib/python3.8/multiprocessing/synchronize.py(162): __init__
  /tmp/python_env_83tkOi/0/lib/python3.8/multiprocessing/context.py(68): Lock
  /tmp/python_env_83tkOi/0/lib/python3.8/multiprocessing/queues.py(336): __init__
  /tmp/python_env_83tkOi/0/lib/python3.8/multiprocessing/context.py(113): SimpleQueue
  /tmp/python_env_83tkOi/0/lib/python3.8/multiprocessing/pool.py(196): __init__
  /tmp/python_env_83tkOi/0/lib/python3.8/multiprocessing/pool.py(925): __init__
  /models/blur_classification/1/blur.py(9): <module>
  <frozen importlib._bootstrap>(219): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(843): exec_module
  <frozen importlib._bootstrap>(686): _load_unlocked
  <frozen importlib._bootstrap>(975): _find_and_load_unlocked
  <frozen importlib._bootstrap>(991): _find_and_load
  /models/blur_classification/1/model.py(6): <module>
  <frozen importlib._bootstrap>(219): _call_with_frames_removed
  <frozen importlib._bootstrap_external>(843): exec_module
  <frozen importlib._bootstrap>(686): _load_unlocked
  <frozen importlib._bootstrap>(975): _find_and_load_unlocked
  <frozen importlib._bootstrap>(991): _find_and_load
;
I0529 10:21:51.291949 1 server.cc:563]
+------------------+------+
| Repository Agent | Path |
+------------------+------+
+------------------+------+
I0529 10:21:51.291992 1 server.cc:590]
+---------+-------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Backend | Path                                                  | Config                                                                                                                                                        |
+---------+-------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------+
| python  | /opt/tritonserver/backends/python/libtriton_python.so | {"cmdline":{"auto-complete-config":"true","min-compute-capability":"6.000000","backend-directory":"/opt/tritonserver/backends","default-max-batch-size":"4"}} |
+---------+-------------------------------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------+
I0529 10:21:51.292083 1 server.cc:633]
+---------------------+---------+----------------------------------------------------------------------------------------+
| Model               | Version | Status                                                                                 |
+---------------------+---------+----------------------------------------------------------------------------------------+
| blur_classification | 1       | UNAVAILABLE: Internal: OSError: [Errno 28] No space left on device                     |
|                     |         |                                                                                        |
|                     |         | At:                                                                                    |
|                     |         |   /tmp/python_env_83tkOi/0/lib/python3.8/multiprocessing/synchronize.py(61): __init__  |
|                     |         |   /tmp/python_env_83tkOi/0/lib/python3.8/multiprocessing/synchronize.py(162): __init__ |
|                     |         |   /tmp/python_env_83tkOi/0/lib/python3.8/multiprocessing/context.py(68): Lock          |
|                     |         |   /tmp/python_env_83tkOi/0/lib/python3.8/multiprocessing/queues.py(336): __init__      |
|                     |         |   /tmp/python_env_83tkOi/0/lib/python3.8/multiprocessing/context.py(113): SimpleQueue  |
|                     |         |   /tmp/python_env_83tkOi/0/lib/python3.8/multiprocessing/pool.py(196): __init__        |
|                     |         |   /tmp/python_env_83tkOi/0/lib/python3.8/multiprocessing/pool.py(925): __init__        |
|                     |         |   /models/blur_classification/1/blur.py(9): <module>                                   |
|                     |         |   <frozen importlib._bootstrap>(219): _call_with_frames_removed                        |
|                     |         |   <frozen importlib._bootstrap_external>(843): exec_module                             |
|                     |         |   <frozen importlib._bootstrap>(686): _load_unlocked                                   |
|                     |         |   <frozen importlib._bootstrap>(975): _find_and_load_unlocked                          |
|                     |         |   <frozen importlib._bootstrap>(991): _find_and_load                                   |
|                     |         |   /models/blur_classification/1/model.py(6): <module>                                  |
|                     |         |   <frozen importlib._bootstrap>(219): _call_with_frames_removed                        |
|                     |         |   <frozen importlib._bootstrap_external>(843): exec_module                             |
|                     |         |   <frozen importlib._bootstrap>(686): _load_unlocked                                   |
|                     |         |   <frozen importlib._bootstrap>(975): _find_and_load_unlocked                          |
|                     |         |   <frozen importlib._bootstrap>(991): _find_and_load                                   |
| preprocess          | 1       | READY                                                                                  |
+---------------------+---------+----------------------------------------------------------------------------------------+
I0529 10:21:51.292682 1 metrics.cc:757] Collecting CPU metrics
I0529 10:21:51.292928 1 tritonserver.cc:2264]
+----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Option                           | Value                                                                                                                                                                                                |
+----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| server_id                        | triton                                                                                                                                                                                               |
| server_version                   | 2.30.0                                                                                                                                                                                               |
| server_extensions                | classification sequence model_repository model_repository(unload_dependents) schedule_policy model_configuration system_shared_memory cuda_shared_memory binary_tensor_data statistics trace logging |
| model_repository_path[0]         | /models                                                                                                                                                                                              |
| model_control_mode               | MODE_NONE                                                                                                                                                                                            |
| strict_model_config              | 0                                                                                                                                                                                                    |
| rate_limit                       | OFF                                                                                                                                                                                                  |
| pinned_memory_pool_byte_size     | 268435456                                                                                                                                                                                            |
| response_cache_byte_size         | 0                                                                                                                                                                                                    |
| min_supported_compute_capability | 6.0                                                                                                                                                                                                  |
| strict_readiness                 | 1                                                                                                                                                                                                    |
| exit_timeout                     | 30                                                                                                                                                                                                   |
+----------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
I0529 10:21:51.293214 1 server.cc:264] Waiting for in-flight requests to complete.
I0529 10:21:51.293235 1 server.cc:280] Timeout 30: Found 0 model versions that have in-flight inferences
I0529 10:21:51.293304 1 server.cc:295] All models are stopped, unloading models
I0529 10:21:51.293315 1 server.cc:302] Timeout 30: Found 1 live models and 0 in-flight non-inference requests
I0529 10:21:52.293448 1 server.cc:302] Timeout 29: Found 1 live models and 0 in-flight non-inference requests
I0529 10:21:52.446514 1 model_lifecycle.cc:579] successfully unloaded 'preprocess' version 1
I0529 10:21:53.293667 1 server.cc:302] Timeout 28: Found 0 live models and 0 in-flight non-inference requests
```

**Triton Information**
Triton version: 23.01
Backend: python with `triton_python_backend_stub`
Deployed on kubernetes. Docker image: nvcr.io/nvidia/tritonserver:23.01-py3 
Model size is small about `587.157 MiB`.

**To Reproduce**
Deployed using seldon-core framework.

```
apiVersion: machinelearning.seldon.io/v1alpha2
kind: SeldonDeployment
metadata:
  name: model-test-triton
  namespace: model-test
spec:
  name: model-test
  protocol: kfserving
  predictors:
  - componentSpecs:
    - spec:
        volumes:
        - name: model-provision-location
          emptyDir: {}
        initContainers:
        - name: model-model-initializer
          image: seldonio/rclone-storage-initializer:1.14.1
          imagePullPolicy: IfNotPresent
          args:
            - "gcs://<bucket-name>/triton-model/triton"
            - "/models"

          volumeMounts:
            - mountPath: /models
              name: model-provision-location

          envFrom:
            - secretRef:
                name: rclone-config
        containers:
        - name: model
          args:
          - /opt/tritonserver/bin/tritonserver
          - '--grpc-port=9500'
          - '--http-port=9000'
          - '--model-repository=/models'
          - '--strict-model-config=false'
          volumeMounts:
          - mountPath: /models
            name: model-provision-location
            readOnly: true
          env:
          - name: ENV
            value: devel
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 5
            successThreshold: 1
            httpGet:
              path: /v2/health/live
              port: http
              scheme: HTTP
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 20
            periodSeconds: 5
            successThreshold: 1
            httpGet:
              path: /v2/health/ready
              port: http
              scheme: HTTP
            timeoutSeconds: 1
          resources:
            requests:
              cpu: '1'
              memory: 4Gi
            limits:
              cpu: '2'
              memory: 6Gi
        serviceAccountName: <sa>
      hpaSpec:
        maxReplicas: 1
        metrics:
        - resource:
            name: cpu
            targetAverageUtilization: 90
          type: Resource
        minReplicas: 1
    graph:
      children: []
      implementation: TRITON_SERVER
      modelUri: gcs://<bucket-name>/triton-model/triton
      envSecretRefName: rclone-config
      name: model
      parameters: []
    annotations:
      predictor_version: '0.1'
    name: api
    replicas: 1
    svcOrchSpec:
      env:
      - name: SELDON_LOG_LEVEL
        value: DEBUG
```

**Comment by DimasAdinugroho** [comment]
Hi @Tabrizian, this is the code for blur.py. Basically, I tried to use `ThreadPool` in the code. Is this something that I need to avoid? I set the cpu requests: 1 and the limit: 2. 

There is no issue when I tried to deployed on my local using `docker run` command.

```python
import os
import logging
import numpy as np
import tensorflow as tf
from multiprocessing.pool import ThreadPool


CPU_COUNT = os.cpu_count()
THREAD_POOL =  ThreadPool(CPU_COUNT)
BLUR_IMAGE_SIZE = (160, 160)
```

**Comment by DimasAdinugroho** [comment]
Already resolved, this issue is caused due to low storage on shared memory `/dev/shm`. I was able to solved it by adding this on the yaml file.

```
volumes:
    - name: dshm
      emptyDir:
        medium: Memory
volumeMounts:
      - mountPath: /dev/shm
        name: dshm
```
