### ISSUE TITLE
Autoscaling: unable to get metric avg_time_queue_us

### ISSUE THREAD

**Issue by mtaron** [triton-inference-server/server#6247]
**Description**
I am trying to enable autoscaling by following the [k8s-onprem](https://github.com/triton-inference-server/server/blob/main/deploy/k8s-onprem/values.yaml#L54) example, but the Horizontal Pod Autoscaler is returning an error:

```
Warning  FailedComputeMetricsReplicas  29m (x4 over 30m)    horizontal-pod-autoscaler  invalid metrics (1 invalid out of 1), first error is: failed to get pods metric value: unable to get metric avg_time_queue_us: no metrics returned from custom metrics API
```

I have installed Prometheus Adapter using the [prometheus-community Helm chart](https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus-adapter), version 4.3.0.

The config is identical to the k8s-onprem example:

```yaml
rules:
  custom:
    - seriesQuery: 'nv_inference_queue_duration_us{namespace="default",pod!=""}'
      resources:
        overrides:
          namespace:
            resource: "namespace"
          pod:
            resource: "pod"
      name:
        matches: "nv_inference_queue_duration_us"
        as: "avg_time_queue_us"
      metricsQuery: 'avg(delta(nv_inference_queue_duration_us{<<.LabelMatchers>>}[30s])/(1+delta(nv_inference_request_success{<<.LabelMatchers>>}[30s]))) by (<<.GroupBy>>)'
```

I am using the same autoscaling metrics for HPA as described in k8s-onprem example.

```yaml
  metrics:
    - type: Pods
      pods:
        metric:
          name: avg_time_queue_us
        target:
          type: AverageValue
          averageValue: 50
```

It _looks_ like Prometheus Adapter is finding the metrics successfully. If I run `kubectl get --raw '/apis/custom.metrics.k8s.io/v1beta1' | jq`, I see the following:

```json
{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "custom.metrics.k8s.io/v1beta1",
  "resources": [
    {
      "name": "pods/avg_time_queue_us",
      "singularName": "",
      "namespaced": true,
      "kind": "MetricValueList",
      "verbs": [
        "get"
      ]
    },
    {
      "name": "namespaces/avg_time_queue_us",
      "singularName": "",
      "namespaced": false,
      "kind": "MetricValueList",
      "verbs": [
        "get"
      ]
    }
  ]
}
```

I'm not sure how to debug the customer metrics beyond this point.

**Triton Information**
What version of Triton are you using?
**2.36.0**

Are you using the Triton container or did you build it yourself?
Building myself with this script:

```sh
git clone --depth 1 --branch "v$TRITON_RELEASE" https://github.com/triton-inference-server/server.git .

python compose.py \
        --cache redis \
        --cache local \
        --backend identity \
        --backend python \
        --backend onnxruntime \
        --backend pytorch \
        --backend tensorrt \
        --output-name <our registery>/tritonserver:$TRITON_RELEASE
```

**To Reproduce**
Steps to reproduce the behavior.

I believe the [k8s-onprem](https://github.com/triton-inference-server/server/blob/main/deploy/k8s-onprem/values.yaml#L54) example will exhibit this behavior. The only functional difference I can see is that it is using version 3 of Prometheus Adapter, but I am on 4.3.0.

Describe the models (framework, inputs, outputs), ideally include the model configuration file (if using an ensemble include the model configuration file for that as well).

I don't think this is relevant to the bug.

**Expected behavior**

I expect the HPA to be able to read the custom metrics.
