### ISSUE TITLE
[feature request] Static (or mostly static) build instructions (currently build with only  `libboost_filesystem.a` fails)

### ISSUE THREAD

**Issue by vadimkantorov** [triton-inference-server/server#6745]
Uncommenting `sudo rm /lib/*/libboost_filesystem.so*` makes the build fail, but without any specific error message (`libboost_filesystem1.81.a` is indeed existing).

Starting with `r23.12`, `tritonserver` started to require `libboost_filesystem1.81.so`, not just in build time, but also in runtime

It would be nice to have instructions on how to get a static (or mostly static) build to avoid the need for a very recent libboost. I've been using the following GitHub Actions script to obtain a built `tritonserver` binary for reuse on end cpu-only system for testing some python-backend models.

```yaml
name: buildtritoninferenceserver
on: workflow_dispatch

jobs:

  buildtritoninferenceserver:
    runs-on: ubuntu-22.04
    steps:
      - name: Install Prerequisites
        run:  sudo add-apt-repository -y ppa:mhier/libboost-latest && sudo apt-get update && sudo apt-get install -y git build-essential rapidjson-dev libssl-dev libre2-dev libb64-dev libarchive-dev libnuma-dev libboost1.81-dev libboost-filesystem1.81-dev

#      - name: Keep only static libboost_filesystem.a
#        run:  sudo rm /lib/*/libboost_filesystem.so* && ls /lib/*/libboost_filesystem*

      - name: Clone Triton
        run: git clone https://github.com/triton-inference-server/server --branch r23.12 --single-branch --depth 1

      - name: Build Triton
        run: cd server && python ./build.py -v --no-container-build --enable-logging --enable-stats --enable-tracing --build-dir="$PWD/build" --backend python --backend=ensemble --extra-core-cmake-arg=TRITON_ENABLE_GRPC=OFF --extra-core-cmake-arg=TRITON_ENABLE_HTTP=ON  --extra-core-cmake-arg=TRITON_ENABLE_ENSEMBLE=ON

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: opt
          path: server/build/opt/
```
