### ISSUE TITLE
[400] 'MODEL' version 1 is not at ready state even if /v2/health/ready has succeeded

### ISSUE THREAD

**Issue by ShuaiShao93** [triton-inference-server/server#6939]
**Description**
Got `[400] Request for unknown model: 'MODEL' version 1 is not at ready state` even if we have the startup Probe and readinessProbe in k8s config:
```
    startupProbe:
      failureThreshold: 60
      httpGet:
        path: /v2/health/ready
        port: http
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    readinessProbe:
        initialDelaySeconds: 5
        periodSeconds: 5
        failureThreshold: 3
        httpGet:
          path: /v2/health/ready
          port: http
```

**Triton Information**
nvcr.io/nvidia/tritonserver:23.11-py3

**To Reproduce**
I can't reproduce it locally for now. But the args we are passing are:
`--model-control-mode=explicit`, `--model-repository=/workspace/models`, "--load-model=MODEL1", "--load-model=MODEL2", "--load-model=MODEL3".

And we use Python backend for these models, and each TritonPythonModel has an `initialize` method that downloads the model.

**Expected behavior**
All models should be ready if /v2/health/ready passes
