### ISSUE TITLE
After load a model, Triton server suddenly not work that it shows CUDA failed to initialize. Unknown error (error 999).

### ISSUE THREAD

**Issue by chiehpower** [triton-inference-server/server#6946]
**Description**

Now I have a laptop, the spec is quite new. Using RTX4070, 32 GB RAM memory and has 24 CPU cores. 
When I start the Triton server, it can detect the GPU device and work well. However, when I moved out the model and put it back again, then it was broken. It shows `The NVIDIA Driver is present, but CUDA failed to initialize. GPU functionality will not be available. [[Unknown error (error 999)]]` and `Unable to destroy DCGM group: setting not configured`

![2024-03-05_08-49](https://github.com/triton-inference-server/server/assets/32332200/efdbcebe-083c-4e4a-a8a1-a85148ca2968)

![image](https://github.com/triton-inference-server/server/assets/32332200/36757a72-c872-4cc5-a844-3ebd1e45f2a0)

**Triton Information**

- Triton Server Container: `v23.08`
- GPU driver version is **535.154.05**

Here is my docker-compose file setting.

```
  tritonserver:
    image: nvcr.io/nvidia/tritonserver:23.02-py3
    deploy:
     resources:
       reservations:
         devices:
         - driver: nvidia
           capabilities: [gpu]
    command: tritonserver --model-store=/models --model-control-mode="poll" --log-info true --strict-model-config=false
    privileged: true
    volumes:
      - /var/database/data/models:/models
    shm_size: 20gb
    ulimits:
      stack: 67108864
    networks:
      webgateway:
        ipv4_address: 172.24.10.3
    container_name: trt_serving
    restart: always
```

**To Reproduce**
It cannot reproduce.

**Expected behavior**
Triton can detect the GPU device.

I have no idea about this problem. Your suggestions would be greatly appreciated.
Thank you.
