### ISSUE TITLE
onnx runtime error 2: not enough space - while running model-analyzer

### ISSUE THREAD

**Issue by pravingadakh** [triton-inference-server/server#6976]
**Description**
We are seeing following error when running model-analyzer profiler. 

```
[Model Analyzer] Initializing GPUDevice handles
[Model Analyzer] Using GPU 0 Tesla V100-PCIE-16GB with UUID GPU-6b9d5651-341e-acc6-921c-551663fcf1d5
[Model Analyzer] WARNING: Overriding the output model repo path "/opt/tritonserver/output_model_repository"
[Model Analyzer] Starting a local Triton Server
[Model Analyzer] Loaded checkpoint from file /opt/tritonserver/checkpoints/10.ckpt
[Model Analyzer] GPU devices match checkpoint - skipping server metric acquisition
[Model Analyzer]
[Model Analyzer] Creating model config: model_relevance_v1_config_default
[Model Analyzer]
[Model Analyzer] Profiling model_relevance_v1_config_default: client batch size=1, concurrency=5
[Model Analyzer] Running perf_analyzer failed with exit status 99:
 Successfully read data for 1 stream/streams with 1 step/steps.
*** Measurement Settings ***
  Batch size: 1
  Using "time_windows" mode for stabilization
  Measurement window: 5000 msec
  Using synchronous calls for inference
  Stabilizing using p95 latency

Request concurrency: 5
Failed to maintain requested inference load. Worker thread(s) failed to generate concurrent requests.
Thread [0] had error: onnx runtime error 2: not enough space: expected 21600, got 18000

Thread [1] had error: onnx runtime error 2: not enough space: expected 21600, got 18000

Thread [2] had error: onnx runtime error 2: not enough space: expected 21600, got 18000

Thread [3] had error: onnx runtime error 2: not enough space: expected 21600, got 18000

Thread [4] had error: onnx runtime error 2: not enough space: expected 21600, got 18000
```

**Triton Information**
What version of Triton are you using?

`nvcr.io/nvidia/tritonserver:22.09-py3`

**To Reproduce**
Steps to reproduce the behavior.

Run model-analyzer with following config file

`model-analyzer profile -f config.yaml`

config.yaml

```
model_repository: /mnt/models
override_output_model_repository: true

profile_models:
  model_relevance_v1:
    parameters:
      concurrency:
        start: 5
        stop: 25
        step: 5
      batch_sizes: 1

inference_output_fields: model_name,batch_size,concurrency,model_config_path,instance_group,max_batch_size,satisfies_constraints,perf_throughput,perf_latency_p99,perf_latency_p95

perf_analyzer_flags:
  percentile: 95
  measurement-mode: time_windows
  input-data: /opt/tritonserver/data_50_54.json
  shape:
      - input_ids:50,54
      - token_type_ids:50,54
      - attention_mask:50,54
```

**Expected behavior**
Expected model-analyzer to run successfully.
