### ISSUE TITLE
Memory Leak in NVIDIA Triton Server (v24.09-py3) with model-control-mode=explicit

### ISSUE THREAD

**Issue by Mustafiz48** [triton-inference-server/server#7727]
This issue reports a potential memory leak observed when running NVIDIA Triton Server (v24.09-py3) with model-control-mode=explicit. The server seems to hold onto physical RAM after inference requests are completed, leading to memory exhaustion over time.

I am using triton inference server to host [segment anything model by facebook](https://github.com/facebookresearch/segment-anything). I have exported the encoder part to ONNX format with [this notebook](https://github.com/AndreyGermanov/sam_onnx_full_export/blob/main/sam_onnx_export.ipynb). With the following code, I am running inference only on the sam_encoder model, which is onnx model hosted with triton [24.09]. 

I am using following code to test the inference server:

```
import time
import numpy as np
import tritonclient
import tritonclient.http as httpclient
import requests

inference_server_url = "http://localhost:8000"
triton_server = httpclient.InferenceServerClient(url="localhost:8000")

model_name = "sam_encoder"
n= 10 # Number of inference to test

def load_model(model_name):
    print(f"loading model: {model_name}")
    response = requests.post(f"{inference_server_url}/v2/repository/models/{model_name}/load")
    if response.status_code == 200:
        print(f"Model {model_name} loaded successfully.")
    else:
        print(f"Failed to load model {model_name}: {response.text}")


def unload_model(model_name):
    print(f"Unloading model: {model_name}")
    response = requests.post(f"{inference_server_url}/v2/repository/models/{model_name}/unload")
    if response.status_code == 200:
        print(f"Model {model_name} unloaded successfully.")
    else:
        print(f"Failed to unload model {model_name}: {response.text}")


with open(f"input_tensor_{model_name}.txt", 'r') as file:
    input_tensor = eval(file.read(), {'array':np.array, "float32": np.float32})

input_tensor_inference = tritonclient.http.InferInput("images", input_tensor.shape, datatype="FP32")
input_tensor_inference.set_data_from_numpy(input_tensor)



for i in range(n):
    print(f"\n{i+1}/{n}: calling inference server....")
    load_model(model_name)
    embedding_result = triton_server.infer(model_name=model_name, inputs=[input_tensor_inference])
    image_embedding = embedding_result.as_numpy("embeddings")
    unload_model(model_name)

    print("Got response from the inference server")
    time.sleep(3)

```

Here is the docker-compose.yml file I am using to run the tritron server:

```
services:
  triton:
    image: nvcr.io/nvidia/tritonserver:24.09-py3
    container_name: triton-server
    runtime: nvidia
    command: tritonserver --model-repository=/models --model-control-mode=explicit
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
    volumes:
      - ./model-repository:/models
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

```

Here is the [input file to test the code](https://drive.google.com/file/d/1tZdaM040ffrh2-91Fd3WSttRUKcWvwy1/view?usp=sharing). 

When I run the code, ite executes properly. But it keep holding physical ram. After the inference is done, it doesn't release the physical memory. With load method, it loads the model into gpu, with unload it realeases the model from gpu. So with GPU we don't have any issue. 

But the physical RAM is growing with more requests. Here's the graph showing RAM usage by tritron. 

![triton_holding_ram](https://github.com/user-attachments/assets/7b73037f-9d75-490f-8619-5b966ca69e2d)

Even if it comes to a saturation points where it dosen't consumes any more ram for the same model (for example: sam_encoder.onnx), it doesn't realease that RAM. So if I try to perform inference with some new other model, it will start consuming that RAM for that model also. Eventually it consumes all the RAM of the machine and leads to frozen state. If we delete the tritron container, it instantly releases the memory.
