### ISSUE TITLE
GPU instances not supported on Jetson Orin AGX 64GB with JetPack 6.2

### ISSUE THREAD

**Issue by tiwaojo** [triton-inference-server/server#8183]
**Description**
Hello, I am trying to setup an ensemble model from 2 hugging face models on a Jetson Orin AGX 64GB via docker but encountered the error below
<details><summary>Error Log</summary>
<p>

+-------------+-------------+-------------------------------------------------------------------------------+
| Model    | Version | Status                                                                                      |
+-------------+------------+--------------------------------------------------------------------------------+
| model_1| 1            | UNAVAILABLE: Internal: GPU instances not supported |
| model_2| 1            | UNAVAILABLE: Internal: GPU instances not supported |
+------------+-------------+-------------------------------------------------------------------------------+

</p>
</details> 

According to the [jetson.md](https://github.com/triton-inference-server/server/blob/r25.03/docs/user_guide/jetson.md) docs and supporting [information](https://github.com/triton-inference-server/server/issues/6588#issuecomment-1815159959), it mentions the JetPack 5.0 does not support GPU tensors on the Python Backend.

Is this exclusive to JetPack 5.0 or does it also apply to JetPack 6.0 and above?

**Triton Information**
Triton Server Version: 2.56.0
JetPack Version: nvidia-l4t-core 36.4.3-20250107174145
Docker Image: nvcr.io/nvidia/tritonserver:25.03-py3-igpu (Base Image)

<details><summary>Docker Compose</summary>
<p>

```yaml
services:
  triton-lpr:
    image: registry.io/library/triton-l4t:jp36.4.0-agx
    container_name: triton-lpr
    runtime: nvidia
    network_mode: host
    shm_size: 1gb
    entrypoint: [
                "/opt/tritonserver/bin/tritonserver",
                "--model-repository=/triton_models",
                "--allow-grpc=false",
                "--allow-http=true",
                "--allow-gpu-metrics=true",
                "--log-verbose=1",
                "--log-file=/triton_server_logs/triton.log",
                "--backend-directory=/opt/tritonserver/backends",
                "--exit-timeout-secs=30"
                ]
    volumes:
      - $PWD/triton_models:/triton_models:ro
      - $PWD/logs:/triton_server_logs:rw
      # Option to mount all cached models on the host system
      - ${PWD}/.cache/huggingface:/root/.cache/huggingface:rw
```

</p>
</details> 

Thank you.
