### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 40692

### ISSUE THREAD

**Issue by omerap12** [triton-inference-server/server#8240]
**Description**
I am trying to run Triton server on EKS.
The env variables of the image are as follows:
```yaml
env:
  - name: MODEL_CONTROL
    value: "poll"
  - name: REPOSITORY_POLL_SECS
    value: "5"
  - name: TMPDIR
    value: "/tmp"
  - name: HUGGING_FACE_HUB_TOKEN
    value: TOKEN
  - name: HF_HOME
    value: "/cache"
  - name: CUDA_VISIBLE_DEVICES
    value: "0,1,2,3"
  - name: PYTORCH_CUDA_ALLOC_CONF
    value: "expandable_segments:True"
  - name: TORCH_COMPILE_DISABLE
```
The model configuration is as follows:
```yaml
{
    "model": "meta-llama/Llama-4-Scout-17B-16E",
     "disable_log_requests": "true",
    "gpu_memory_utilization": 0.95,
    "tensor_parallel_size": 4,
    "enforce_eager": "true",
    "disable_custom_all_reduce": "true",
    "max_model_len": 16384
}
```

I'm using the vllm image ( see below ).
I get the following error:
```bash
(VllmWorkerProcess pid=470) ERROR 06-09 11:32:10 [multiproc_worker_utils.py:238]                 ^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=470) ERROR 06-09 11:32:10 [multiproc_worker_utils.py:238]   File "/usr/local/lib/python3.12/dist-packages/triton/runtime/driver.py", line 9, in _create_driver
(VllmWorkerProcess pid=470) ERROR 06-09 11:32:10 [multiproc_worker_utils.py:238]     return actives[0]()
(VllmWorkerProcess pid=470) ERROR 06-09 11:32:10 [multiproc_worker_utils.py:238]            ^^^^^^^^^^^^
(VllmWorkerProcess pid=470) ERROR 06-09 11:32:10 [multiproc_worker_utils.py:238]   File "/usr/local/lib/python3.12/dist-packages/triton/backends/nvidia/driver.py", line 371, in __init__
(VllmWorkerProcess pid=470) ERROR 06-09 11:32:10 [multiproc_worker_utils.py:238]     self.utils = CudaUtils()  # TODO: make static
(VllmWorkerProcess pid=470) ERROR 06-09 11:32:10 [multiproc_worker_utils.py:238]                  ^^^^^^^^^^^
(VllmWorkerProcess pid=470) ERROR 06-09 11:32:10 [multiproc_worker_utils.py:238]   File "/usr/local/lib/python3.12/dist-packages/triton/backends/nvidia/driver.py", line 80, in __init__
(VllmWorkerProcess pid=470) ERROR 06-09 11:32:10 [multiproc_worker_utils.py:238]     mod = compile_module_from_src(Path(os.path.join(dirname, "driver.c")).read_text(), "cuda_utils")
(VllmWorkerProcess pid=470) ERROR 06-09 11:32:10 [multiproc_worker_utils.py:238]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=470) ERROR 06-09 11:32:10 [multiproc_worker_utils.py:238]   File "/usr/local/lib/python3.12/dist-packages/triton/backends/nvidia/driver.py", line 57, in compile_module_from_src
(VllmWorkerProcess pid=470) ERROR 06-09 11:32:10 [multiproc_worker_utils.py:238]     so = _build(name, src_path, tmpdir, library_dirs(), include_dir, libraries)
(VllmWorkerProcess pid=470) ERROR 06-09 11:32:10 [multiproc_worker_utils.py:238]                                         ^^^^^^^^^^^^^^
(VllmWorkerProcess pid=470) ERROR 06-09 11:32:10 [multiproc_worker_utils.py:238]   File "/usr/local/lib/python3.12/dist-packages/triton/backends/nvidia/driver.py", line 45, in library_dirs
(VllmWorkerProcess pid=470) ERROR 06-09 11:32:10 [multiproc_worker_utils.py:238]     return [libdevice_dir, *libcuda_dirs()]
(VllmWorkerProcess pid=470) ERROR 06-09 11:32:10 [multiproc_worker_utils.py:238]                             ^^^^^^^^^^^^^^
(VllmWorkerProcess pid=470) ERROR 06-09 11:32:10 [multiproc_worker_utils.py:238]   File "/usr/local/lib/python3.12/dist-packages/triton/backends/nvidia/driver.py", line 24, in libcuda_dirs
(VllmWorkerProcess pid=470) ERROR 06-09 11:32:10 [multiproc_worker_utils.py:238]     libs = subprocess.check_output(["/sbin/ldconfig", "-p"]).decode()
(VllmWorkerProcess pid=470) ERROR 06-09 11:32:10 [multiproc_worker_utils.py:238]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(VllmWorkerProcess pid=470) ERROR 06-09 11:32:10 [multiproc_worker_utils.py:238] UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 40692: invalid continuation byte
ERROR 06-09 11:32:10 [engine.py:448] 'utf-8' codec can't decode byte 0xc4 in position 40692: invalid continuation byte
```

**Triton Information**
What version of Triton are you using?
```bash
image: "nvcr.io/nvidia/tritonserver:25.05-vllm-python-py3"
```

Are you using the Triton container or did you build it yourself?
Yes, see above.

**To Reproduce**
I am using EKS. with the above configuration with instance p4d.

When I ran the above configuration and changed the model name to:
```bash
meta-llama/Llama-3.3-70B-Instruct
```
The model worked as expected. Not sure if this error comes from vllm or Triton ( opened issue there also ).

**Expected behavior**
Model should be served as expected.
